In [ ]:
import sys
sys.path.append("../..")
from src.training import helpers as tr_h
import scanpy as sc

adata = sc.read("/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-08-14-01/data.h5ad")
adata = sc.read("/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-08-14-01/data.h5ad")

In [ ]:
adata

In [80]:
ls ../../data

annotation_pancreas/  pp_data-24-09-24-02/  pp_data-25-04-29-05/
cellxgene/            pp_data-24-09-24-03/  pp_data-25-05-01-01/
ms/                   pp_data-24-09-25-01/  pp_data-25-05-01-02/
pp_data-24-08-26-01/  pp_data-24-09-25-02/  pp_data-25-05-01-03/
pp_data-24-09-02-01/  pp_data-24-09-25-03/  pp_data-25-05-01-04/
pp_data-24-09-04-01/  pp_data-24-10-06-01/  pp_data-25-05-01-05/
pp_data-24-09-05-01/  pp_data-24-11-07-01/  pp_data-25-05-07-01/
pp_data-24-09-09-01/  pp_data-24-11-10-01/  pp_data-25-05-07-02/
pp_data-24-09-09-02/  pp_data-24-11-11-01/  pp_data-25-08-12-01/
pp_data-24-09-13-01/  pp_data-24-11-12-01/  pp_data-25-08-12-02/
pp_data-24-09-14-01/  pp_data-24-11-13-01/  pp_data-25-08-14-01/
pp_data-24-09-15-01/  pp_data-25-04-29-01/  README.md
pp_data-24-09-22-01/  pp_data-25-04-29-02/  test_1/
pp_data-24-09-23-01/  pp_data-25-04-29-03/
pp_data-24-09-24-01/  pp_data-25-04-29-04/

In [93]:
adata.obs["sample_ids"] = [x.split(".")[1] for x in adata.obs["ids"]]
adata.obs.drop_duplicates(subset=["sample_ids"]).shape

(30150, 17)

In [ ]:
adata.obs["sample_ids"] = [x.split(".")[1] for x in adata.obs["ids"]]
adata.obs.drop_duplicates(subset=["sample_ids"]).shape

In [ ]:
# with controls - we see some samples can be in some cases controls others disease
adata.obs.groupby("sample_ids")["doid_id"].nunique().sort_values(ascending=False)

sample_ids
TCGA-QK-A6V9-01A    2
TCGA-QK-A6IJ-01A    2
TCGA-QK-A6II-01A    2
TCGA-QK-A6IH-01A    2
TCGA-QK-A6IG-01A    2
                   ..
GSM3529438          1
GSM3529437          1
GSM3529436          1
GSM3529435          1
GSM3529449          1
Name: doid_id, Length: 30150, dtype: int64

In [88]:
# only disease  - drop controls
adata.obs[adata.obs["doid_id"] != "Control"].groupby("sample_ids")["doid_id"].nunique().sort_values(ascending=False)

sample_ids
ERR6212579    2
ERR6212578    2
ERR6212577    2
ERR6212576    2
ERR6212575    2
             ..
GSM3636492    1
GSM3636491    1
GSM3636490    1
GSM3636489    1
GSM3636498    1
Name: doid_id, Length: 19283, dtype: int64

In [91]:
adata.obs.query("sample_ids == 'GSM5971892'")

,ids,dataset,dataset_id,batch,batch_id,dsaid,tissue,n_genes,disease,celltype,disease_study,library,doid_study,doid_id,do_id,doid_disease,sample_ids
17958,DSA05214.GSM5971892.Case,GSE199403,GSE199403,79,79,DSA05214,Lung,19344,Lung Disease,Lung Disease,Lung Disease,RNA-Seq,D,DOID:850,DOID:850,lung disease,GSM5971892
17987,DSA05215.GSM5971892.Case,GSE199403,GSE199403,79,79,DSA05215,Lung,19344,Lung Disease,Lung Disease,Lung Disease,RNA-Seq,D,DOID:850,DOID:850,lung disease,GSM5971892

In [21]:
results = list()
for n_samples in [1,2,3,4,5,6]:
    for n_datasets in [2,3,4,5,6]:
        adata_f = tr_h.clean_adata_qc(adata, n_samples=n_samples, n_dt=n_datasets)
        results.append({"thr_samples": n_samples, "thr_datasets": n_datasets, "n_datasets": adata_f.obs["dataset"].nunique(), "n_doids": adata_f.obs["doid_id"].nunique(), "n_samples": adata_f.shape[0], "n_samples_2": adata_f.obs["sample_ids"].nunique()})

Nº of datasets with +1 control samples: 660
Nº of datasets with +1 disease samples: 660
Nº of datasets with +1 samples (control and disease): 660
adata shape after filtering datasets with +1 samples: (35626, 20608)
Nº of passed diseases 131/ 131
Nº of passed dsaids 1159/ 1159
Nº of datasets with +1 control samples: 660
Nº of datasets with +1 disease samples: 660
Nº of datasets with +1 samples (control and disease): 660
adata shape after filtering datasets with +1 samples: (35626, 20608)
Nº of passed diseases 81/ 131
Nº of passed dsaids 987/ 1159
Nº of datasets with +1 control samples: 660
Nº of datasets with +1 disease samples: 660
Nº of datasets with +1 samples (control and disease): 660
adata shape after filtering datasets with +1 samples: (35626, 20608)
Nº of passed diseases 60/ 131
Nº of passed dsaids 892/ 1159
Nº of datasets with +1 control samples: 660
Nº of datasets with +1 disease samples: 660
Nº of datasets with +1 samples (control and disease): 660
adata shape after filtering datasets with +1 samples: (35626, 20608)
Nº of passed diseases 43/ 131
Nº of passed dsaids 780/ 1159
Nº of datasets with +1 control samples: 660
Nº of datasets with +1 disease samples: 660
Nº of datasets with +1 samples (control and disease): 660
adata shape after filtering datasets with +1 samples: (35626, 20608)
Nº of passed diseases 35/ 131
Nº of passed dsaids 710/ 1159
Nº of datasets with +2 control samples: 660
Nº of datasets with +2 disease samples: 660
Nº of datasets with +2 samples (control and disease): 660
adata shape after filtering datasets with +2 samples: (35626, 20608)
Nº of passed diseases 131/ 131
Nº of passed dsaids 1159/ 1159
Nº of datasets with +2 control samples: 660
Nº of datasets with +2 disease samples: 660
Nº of datasets with +2 samples (control and disease): 660
adata shape after filtering datasets with +2 samples: (35626, 20608)
Nº of passed diseases 81/ 131
Nº of passed dsaids 987/ 1159
Nº of datasets with +2 control samples: 660
Nº of datasets with +2 disease samples: 660
Nº of datasets with +2 samples (control and disease): 660
adata shape after filtering datasets with +2 samples: (35626, 20608)
Nº of passed diseases 60/ 131
Nº of passed dsaids 892/ 1159
Nº of datasets with +2 control samples: 660
Nº of datasets with +2 disease samples: 660
Nº of datasets with +2 samples (control and disease): 660
adata shape after filtering datasets with +2 samples: (35626, 20608)
Nº of passed diseases 43/ 131
Nº of passed dsaids 780/ 1159
Nº of datasets with +2 control samples: 660
Nº of datasets with +2 disease samples: 660
Nº of datasets with +2 samples (control and disease): 660
adata shape after filtering datasets with +2 samples: (35626, 20608)
Nº of passed diseases 35/ 131
Nº of passed dsaids 710/ 1159
Nº of datasets with +3 control samples: 621
Nº of datasets with +3 disease samples: 632
Nº of datasets with +3 samples (control and disease): 614
adata shape after filtering datasets with +3 samples: (35338, 20608)
Nº of passed diseases 126/ 131
Nº of passed dsaids 1104/ 1113
Nº of datasets with +3 control samples: 621
Nº of datasets with +3 disease samples: 632
Nº of datasets with +3 samples (control and disease): 614
adata shape after filtering datasets with +3 samples: (35338, 20608)
Nº of passed diseases 74/ 131
Nº of passed dsaids 923/ 1113
Nº of datasets with +3 control samples: 621
Nº of datasets with +3 disease samples: 632
Nº of datasets with +3 samples (control and disease): 614
adata shape after filtering datasets with +3 samples: (35338, 20608)
Nº of passed diseases 56/ 131
Nº of passed dsaids 845/ 1113
Nº of datasets with +3 control samples: 621
Nº of datasets with +3 disease samples: 632
Nº of datasets with +3 samples (control and disease): 614
adata shape after filtering datasets with +3 samples: (35338, 20608)
Nº of passed diseases 40/ 131
Nº of passed dsaids 727/ 1113
Nº of datasets with +3 control samples: 621
Nº of datasets with +3 disease samples: 632
Nº of datasets with +3 samples (control and disease): 614
adata shape after filtering datasets with +3 samples: (35338, 20608)
Nº of passed diseases 31/ 131
Nº of passed dsaids 651/ 1113
Nº of datasets with +4 control samples: 542
Nº of datasets with +4 disease samples: 560
Nº of datasets with +4 samples (control and disease): 523
adata shape after filtering datasets with +4 samples: (34562, 20608)
Nº of passed diseases 110/ 127
Nº of passed dsaids 996/ 1022
Nº of datasets with +4 control samples: 542
Nº of datasets with +4 disease samples: 560
Nº of datasets with +4 samples (control and disease): 523
adata shape after filtering datasets with +4 samples: (34562, 20608)
Nº of passed diseases 60/ 127
Nº of passed dsaids 803/ 1022
Nº of datasets with +4 control samples: 542
Nº of datasets with +4 disease samples: 560
Nº of datasets with +4 samples (control and disease): 523
adata shape after filtering datasets with +4 samples: (34562, 20608)
Nº of passed diseases 44/ 127
Nº of passed dsaids 704/ 1022
Nº of datasets with +4 control samples: 542
Nº of datasets with +4 disease samples: 560
Nº of datasets with +4 samples (control and disease): 523
adata shape after filtering datasets with +4 samples: (34562, 20608)
Nº of passed diseases 34/ 127
Nº of passed dsaids 643/ 1022
Nº of datasets with +4 control samples: 542
Nº of datasets with +4 disease samples: 560
Nº of datasets with +4 samples (control and disease): 523
adata shape after filtering datasets with +4 samples: (34562, 20608)
Nº of passed diseases 25/ 127
Nº of passed dsaids 559/ 1022
Nº of datasets with +5 control samples: 485
Nº of datasets with +5 disease samples: 511
Nº of datasets with +5 samples (control and disease): 463
adata shape after filtering datasets with +5 samples: (33718, 20608)
Nº of passed diseases 97/ 121
Nº of passed dsaids 901/ 953
Nº of datasets with +5 control samples: 485
Nº of datasets with +5 disease samples: 511
Nº of datasets with +5 samples (control and disease): 463
adata shape after filtering datasets with +5 samples: (33718, 20608)
Nº of passed diseases 53/ 121
Nº of passed dsaids 729/ 953
Nº of datasets with +5 control samples: 485
Nº of datasets with +5 disease samples: 511
Nº of datasets with +5 samples (control and disease): 463
adata shape after filtering datasets with +5 samples: (33718, 20608)
Nº of passed diseases 40/ 121
Nº of passed dsaids 651/ 953
Nº of datasets with +5 control samples: 485
Nº of datasets with +5 disease samples: 511
Nº of datasets with +5 samples (control and disease): 463
adata shape after filtering datasets with +5 samples: (33718, 20608)
Nº of passed diseases 31/ 121
Nº of passed dsaids 588/ 953
Nº of datasets with +5 control samples: 485
Nº of datasets with +5 disease samples: 511
Nº of datasets with +5 samples (control and disease): 463
adata shape after filtering datasets with +5 samples: (33718, 20608)
Nº of passed diseases 22/ 121
Nº of passed dsaids 505/ 953
Nº of datasets with +6 control samples: 446
Nº of datasets with +6 disease samples: 461
Nº of datasets with +6 samples (control and disease): 420
adata shape after filtering datasets with +6 samples: (33133, 20608)
Nº of passed diseases 89/ 119
Nº of passed dsaids 833/ 900
Nº of datasets with +6 control samples: 446
Nº of datasets with +6 disease samples: 461
Nº of datasets with +6 samples (control and disease): 420
adata shape after filtering datasets with +6 samples: (33133, 20608)
Nº of passed diseases 49/ 119
Nº of passed dsaids 667/ 900
Nº of datasets with +6 control samples: 446
Nº of datasets with +6 disease samples: 461
Nº of datasets with +6 samples (control and disease): 420
adata shape after filtering datasets with +6 samples: (33133, 20608)
Nº of passed diseases 38/ 119
Nº of passed dsaids 602/ 900
Nº of datasets with +6 control samples: 446
Nº of datasets with +6 disease samples: 461
Nº of datasets with +6 samples (control and disease): 420
adata shape after filtering datasets with +6 samples: (33133, 20608)
Nº of passed diseases 26/ 119
Nº of passed dsaids 516/ 900
Nº of datasets with +6 control samples: 446
Nº of datasets with +6 disease samples: 461
Nº of datasets with +6 samples (control and disease): 420
adata shape after filtering datasets with +6 samples: (33133, 20608)
Nº of passed diseases 20/ 119
Nº of passed dsaids 456/ 900

In [23]:
import pandas as pd
pd.DataFrame(results)

    thr_samples  thr_datasets  n_datasets  n_doids  n_samples  n_samples_2
0             1             2         660      132      35626        30150
1             1             3         575       82      28203        24648
2             1             4         518       61      24168        21795
3             1             5         453       44      20143        18559
4             1             6         414       36      18830        17310
5             2             2         660      132      35626        30150
6             2             3         575       82      28203        24648
7             2             4         518       61      24168        21795
8             2             5         453       44      20143        18559
9             2             6         414       36      18830        17310
10            3             2         611      127      33508        29233
11            3             3         522       75      27404        23957
12            3             4         472       57      23786        21419
13            3             5         411       41      19681        18127
14            3             6         367       32      17944        16464
15            4             2         509      111      31563        27328
16            4             3         425       61      25057        21934
17            4             4         379       45      21797        19696
18            4             5         343       35      18787        17272
19            4             6         299       26      16910        15455
20            5             2         442       98      29567        25489
21            5             3         369       54      23857        20865
22            5             4         332       41      21143        19056
23            5             5         300       32      18027        16514
24            5             6         256       23      15457        14298
25            6             2         393       90      28781        24764
26            6             3         328       50      22902        20015
27            6             4         298       39      19919        17855
28            6             5         254       27      16082        14793
29            6             6         225       21      14576        13458

In [71]:
import importlib
importlib.reload(tr_h)

In [76]:
adata_f = tr_h.clean_adata_qc(adata, n_samples=2, n_dt=5)

# split
df_obs = adata_f.obs
test_obs = tr_h.split_stratified(
    df=df_obs,
    y_label="doid_id",  # should ALWAYS be on DOID! - OR  celltype be DOID! 
    group_label="dataset_id",
    split_size=10,
    seed=42,
)
tr_h.report_split(test_obs)

Nº of datasets with +2 control samples: 660
Nº of datasets with +2 disease samples: 660
Nº of datasets with +2 samples (control and disease): 660
adata shape after filtering datasets with +2 samples: (35626, 20608)
Nº of passed diseases 43/ 131
Nº of passed dsaids 780/ 1159
df shape: (20143, 17)
df diseases: (11546, 17)
All Labels: 44 ['Control', 'DOID:0050156', 'DOID:0080199', 'DOID:0081087', 'DOID:10286', 'DOID:10591', 'DOID:10652', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:12377', 'DOID:12858', 'DOID:12930', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1909', 'DOID:2377', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3068', 'DOID:3083', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3911', 'DOID:5015', 'DOID:5419', 'DOID:5844', 'DOID:6000', 'DOID:7148', 'DOID:8398', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9352', 'DOID:9744', 'DOID:9970']
Remove Controls - Labels: 43 ['DOID:0050156', 'DOID:0080199', 'DOID:0081087', 'DOID:10286', 'DOID:10591', 'DOID:10652', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:12377', 'DOID:12858', 'DOID:12930', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1909', 'DOID:2377', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3068', 'DOID:3083', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3911', 'DOID:5015', 'DOID:5419', 'DOID:5844', 'DOID:6000', 'DOID:7148', 'DOID:8398', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9352', 'DOID:9744', 'DOID:9970']
Nº of diseases in train split test_split_1:	51
Nº of diseases in test split test_split_1:	45
Nº of datasets in train split test_split_1:	405
Nº of datasets in test split test_split_1:	48
Nº of samples in train split test_split_1:	18768
Nº of samples in test split test_split_1:	1375

In [77]:
test_obs[test_obs["test_split_1"] == 0]

,ids,dataset,dataset_id,batch,batch_id,dsaid,tissue,n_genes,disease,celltype,disease_study,library,doid_study,doid_id,do_id,doid_disease,sample_ids,test_split_1
50,DSA00030.GSM6634377.Control,GSE215424,GSE215424,461,461,DSA00030,Muscle,19402,Control,Control,Amyotrophic Lateral Sclerosis,RNA-Seq,D,Control,Control,Control,GSM6634377,0
51,DSA00030.GSM6634378.Control,GSE215424,GSE215424,461,461,DSA00030,Muscle,19402,Control,Control,Amyotrophic Lateral Sclerosis,RNA-Seq,D,Control,Control,Control,GSM6634378,0
52,DSA00030.GSM6634379.Control,GSE215424,GSE215424,461,461,DSA00030,Muscle,19402,Control,Control,Amyotrophic Lateral Sclerosis,RNA-Seq,D,Control,Control,Control,GSM6634379,0
53,DSA00030.GSM6634380.Control,GSE215424,GSE215424,461,461,DSA00030,Muscle,19402,Control,Control,Amyotrophic Lateral Sclerosis,RNA-Seq,D,Control,Control,Control,GSM6634380,0
54,DSA00030.GSM6634381.Control,GSE215424,GSE215424,461,461,DSA00030,Muscle,19402,Control,Control,Amyotrophic Lateral Sclerosis,RNA-Seq,D,Control,Control,Control,GSM6634381,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35593,DSA10102.GSM4990516.Control,GSE163908,GSE163908,212,212,DSA10102,nan,19402,Control,Control,Idiopathic Pulmonary Fibrosis,RNA-Seq,D,Control,Control,Control,GSM4990516,0
35594,DSA10102.GSM4990517.Control,GSE163908,GSE163908,212,212,DSA10102,nan,19402,Control,Control,Idiopathic Pulmonary Fibrosis,RNA-Seq,D,Control,Control,Control,GSM4990517,0
35595,DSA10102.GSM4990518.Case,GSE163908,GSE163908,212,212,DSA10102,nan,19402,Idiopathic Pulmonary Fibrosis,Idiopathic Pulmonary Fibrosis,Idiopathic Pulmonary Fibrosis,RNA-Seq,D,DOID:0050156,DOID:0050156,idiopathic pulmonary fibrosis,GSM4990518,0
35596,DSA10102.GSM4990519.Case,GSE163908,GSE163908,212,212,DSA10102,nan,19402,Idiopathic Pulmonary Fibrosis,Idiopathic Pulmonary Fibrosis,Idiopathic Pulmonary Fibrosis,RNA-Seq,D,DOID:0050156,DOID:0050156,idiopathic pulmonary fibrosis,GSM4990519,0
35597,DSA10102.GSM4990520.Case,GSE163908,GSE163908,212,212,DSA10102,nan,19402,Idiopathic Pulmonary Fibrosis,Idiopathic Pulmonary Fibrosis,Idiopathic Pulmonary Fibrosis,RNA-Seq,D,DOID:0050156,DOID:0050156,idiopathic pulmonary fibrosis,GSM4990520,0

In [95]:

valid_obs = tr_h.split_stratified(
    df=test_obs[test_obs["test_split_1"]==0],
    y_label="doid_id",  # should ALWAYS be on DOID! - OR  celltype be DOID! 
    group_label="dataset_id",
    split_size=10,
    seed=42,
    new_label="valid_split_1"
)
tr_h.report_split(valid_obs, split_label="valid_split_1")
mask_train = valid_obs["valid_split_1"] == 0
mask_valid = valid_obs["valid_split_1"] == 1

df shape: (18768, 18)
df diseases: (10810, 18)
All Labels: 44 ['Control', 'DOID:0050156', 'DOID:0080199', 'DOID:0081087', 'DOID:10286', 'DOID:10591', 'DOID:10652', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:12377', 'DOID:12858', 'DOID:12930', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1909', 'DOID:2377', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3068', 'DOID:3083', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3911', 'DOID:5015', 'DOID:5419', 'DOID:5844', 'DOID:6000', 'DOID:7148', 'DOID:8398', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9352', 'DOID:9744', 'DOID:9970']
Remove Controls - Labels: 43 ['DOID:0050156', 'DOID:0080199', 'DOID:0081087', 'DOID:10286', 'DOID:10591', 'DOID:10652', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:12377', 'DOID:12858', 'DOID:12930', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1909', 'DOID:2377', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3068', 'DOID:3083', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3911', 'DOID:5015', 'DOID:5419', 'DOID:5844', 'DOID:6000', 'DOID:7148', 'DOID:8398', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9352', 'DOID:9744', 'DOID:9970']
Nº of diseases in train split valid_split_1:	51
Nº of diseases in test split valid_split_1:	44
Nº of datasets in train split valid_split_1:	358
Nº of datasets in test split valid_split_1:	47
Nº of samples in train split valid_split_1:	16986
Nº of samples in test split valid_split_1:	1782

In [103]:
adata.X[mask_train]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 35626 but corresponding boolean dimension is 18768

In [101]:
import numpy as np
idxs_1 = np.argwhere(mask_train.to_numpy())

In [52]:
test_obs.columns

Index(['ids', 'dataset', 'dataset_id', 'batch', 'batch_id', 'dsaid', 'tissue',
       'n_genes', 'disease', 'celltype', 'disease_study', 'library',
       'doid_study', 'doid_id', 'do_id', 'doid_disease', 'sample_ids',
       'test_split_1'],
      dtype='object')

In [45]:
adata.obs[adata.obs["celltype"] == "Williams-Beuren Syndrome"]["doid_id"].unique()

['DOID:1928']
Categories (132, object): ['Control', 'DOID:235', 'DOID:289', 'DOID:332', ..., 'DOID:0060183', 'DOID:0060488', 'DOID:0080199', 'DOID:0081087']

In [104]:
from sklearn.model_selection import train_test_split
# Split to get indices only
train_idx, valid_idx = train_test_split(
    np.arange(len(df_obs)),
    test_size=0.1,
    shuffle=True,
    stratify=df_obs["doid_id"],
)
print(f"train_idx {train_idx.shape}, valid_idx {valid_idx.shape}")

train_idx (18128,), valid_idx (2015,)

In [111]:
list(train_idx)

[246,
 10159,
 1249,
 12865,
 9748,
 10876,
 8855,
 11557,
 11996,
 8990,
 3762,
 17744,
 15191,
 13069,
 16047,
 15980,
 11541,
 13237,
 9219,
 11554,
 611,
 14291,
 14348,
 3766,
 4175,
 4359,
 15029,
 5481,
 4858,
 9326,
 9317,
 12479,
 1229,
 10363,
 10322,
 6625,
 13245,
 18472,
 5617,
 18237,
 1184,
 16113,
 505,
 6899,
 4081,
 10647,
 13783,
 589,
 9884,
 11536,
 16486,
 16952,
 7523,
 12776,
 8478,
 398,
 2161,
 14253,
 6597,
 5196,
 17948,
 13511,
 13945,
 11847,
 17914,
 18942,
 15847,
 7197,
 857,
 9508,
 10949,
 12980,
 5951,
 8644,
 13823,
 4031,
 9752,
 20038,
 18137,
 10863,
 14578,
 855,
 15137,
 4695,
 6401,
 15743,
 2414,
 17876,
 4328,
 2731,
 16455,
 4974,
 9428,
 12262,
 3338,
 12255,
 14151,
 8936,
 10131,
 5932,
 1140,
 19645,
 20090,
 5673,
 1350,
 209,
 4016,
 5652,
 2240,
 2974,
 16987,
 18633,
 9162,
 10273,
 9842,
 15148,
 1467,
 14659,
 698,
 11007,
 7297,
 4855,
 4679,
 6940,
 15814,
 8029,
 4356,
 10871,
 392,
 7027,
 7450,
 2345,
 13356,
 11551,
 19220,
 12297,
 18823,
 3212,
 2095,
 9251,
 14863,
 16893,
 18836,
 2690,
 20060,
 14201,
 17052,
 17900,
 18529,
 7412,
 1347,
 4988,
 14371,
 17935,
 9472,
 13782,
 3326,
 10417,
 18284,
 7563,
 14013,
 3671,
 2782,
 15901,
 12565,
 1907,
 5721,
 17790,
 7612,
 15599,
 17146,
 9777,
 12677,
 17013,
 812,
 8862,
 3730,
 15445,
 292,
 7622,
 5957,
 5382,
 18656,
 4116,
 12335,
 10200,
 5453,
 5080,
 8572,
 4506,
 19344,
 7369,
 9464,
 6165,
 16666,
 14523,
 14902,
 7183,
 9128,
 17653,
 4273,
 7963,
 11074,
 170,
 17481,
 11958,
 19679,
 899,
 8278,
 10889,
 775,
 15957,
 13719,
 9871,
 5912,
 18616,
 9755,
 1574,
 5210,
 17105,
 8492,
 3351,
 13924,
 1040,
 7012,
 6389,
 13320,
 15205,
 16653,
 3093,
 1401,
 13970,
 10195,
 7102,
 4627,
 10964,
 17581,
 16810,
 10426,
 15206,
 9095,
 9223,
 19807,
 15696,
 761,
 8345,
 17114,
 11040,
 15979,
 9681,
 8814,
 2977,
 11478,
 10160,
 17247,
 17772,
 3654,
 865,
 15940,
 9764,
 14707,
 9399,
 17774,
 13834,
 2824,
 11053,
 9719,
 2949,
 12991,
 16518,
 18300,
 18618,
 3347,
 1535,
 13815,
 17103,
 18433,
 16667,
 2247,
 11642,
 11903,
 2626,
 8829,
 8784,
 16049,
 5667,
 13888,
 4384,
 14613,
 13367,
 18368,
 16073,
 5553,
 6721,
 3173,
 618,
 160,
 3148,
 11982,
 9234,
 13251,
 9058,
 10618,
 1495,
 8219,
 9233,
 10061,
 15676,
 7359,
 11294,
 16647,
 16759,
 13877,
 12930,
 8653,
 15034,
 1378,
 16037,
 16350,
 4962,
 3651,
 19323,
 12831,
 1940,
 17831,
 10215,
 5201,
 17208,
 7375,
 15447,
 19926,
 15347,
 1938,
 13936,
 7587,
 3375,
 6061,
 3757,
 2498,
 12949,
 1150,
 15158,
 8909,
 1998,
 17847,
 7725,
 17451,
 17121,
 5949,
 16249,
 5799,
 15588,
 10269,
 14815,
 16485,
 14370,
 8060,
 20017,
 9938,
 19001,
 5943,
 2845,
 743,
 8141,
 9959,
 19791,
 15630,
 14462,
 13933,
 6270,
 7542,
 12809,
 6485,
 3172,
 10002,
 13644,
 4557,
 798,
 13637,
 1472,
 4470,
 17632,
 6645,
 15827,
 3882,
 10724,
 13376,
 3708,
 18594,
 15874,
 8071,
 2267,
 20108,
 9052,
 19930,
 3309,
 17840,
 10707,
 8696,
 14931,
 18913,
 13761,
 14380,
 2353,
 12282,
 11928,
 6897,
 8657,
 16162,
 4600,
 13995,
 9902,
 11932,
 7334,
 19390,
 17184,
 5358,
 860,
 7266,
 8749,
 14704,
 12748,
 9374,
 8907,
 9366,
 7368,
 15511,
 18550,
 8884,
 14841,
 13186,
 14454,
 3166,
 7854,
 6739,
 12524,
 9632,
 12460,
 16463,
 8587,
 14468,
 18739,
 6028,
 12279,
 11685,
 4325,
 7862,
 15134,
 18635,
 10931,
 13042,
 1087,
 14492,
 14614,
 16290,
 3339,
 6446,
 5963,
 16563,
 17750,
 4803,
 16211,
 12295,
 361,
 2490,
 18281,
 7088,
 2022,
 8239,
 16085,
 17787,
 4672,
 4559,
 5832,
 8469,
 9608,
 13948,
 13745,
 10757,
 16446,
 6778,
 10156,
 8094,
 19141,
 18884,
 14475,
 15856,
 10333,
 4285,
 2250,
 18296,
 13388,
 5539,
 461,
 14248,
 3313,
 9070,
 4341,
 5538,
 8327,
 4295,
 4374,
 18476,
 12924,
 7917,
 17768,
 657,
 17356,
 1070,
 13297,
 7371,
 973,
 6803,
 3344,
 226,
 3410,
 6785,
 13000,
 14040,
 19234,
 13466,
 6158,
 2370,
 17091,
 10035,
 8526,
 11242,
 2806,
 6132,
 16115,
 11990,
 10821,
 13416,
 6322,
 6593,
 6883,
 2655,
 4582,
 18599,
 7519,
 13802,
 11781,
 18920,
 6745,
 10674,
 8866,
 4693,
 11054,
 14986,
 15444,
 18775,
 102,
 15996,
 13765,
 4095,
 23,
 8218,
 19098,
 131,
 10085,
 3503,
 4084,
 8664,
 18943,
 13618,
 13013,
 17132,
 18336,
 19819,
 17049,
 6231,
 12586,
 12327,
 5827,
 11096,
 1661,
 2700,
 4830,
 5325,
 3010,
 13366,
 524,
 9206,
 11326,
 2064,
 3098,
 14544,
 10854,
 6126,
 18082,
 5850,
 7553,
 5454,
 5222,
 3284,
 6160,
 7546,
 265,
 16733,
 6033,
 15185,
 6153,
 14862,
 10609,
 1560,
 3402,
 13454,
 13272,
 15092,
 19670,
 2960,
 15530,
 1595,
 7750,
 18274,
 6599,
 14241,
 1994,
 6149,
 17127,
 1296,
 1849,
 3442,
 14505,
 346,
 12962,
 19300,
 14306,
 11486,
 11451,
 4556,
 14817,
 4536,
 12737,
 4702,
 601,
 5532,
 17491,
 10101,
 7467,
 17303,
 7128,
 2807,
 9457,
 12706,
 271,
 12120,
 437,
 16078,
 11052,
 3164,
 5390,
 15239,
 7799,
 10505,
 15174,
 12968,
 1280,
 12470,
 3234,
 4027,
 4592,
 560,
 19566,
 3931,
 4134,
 10217,
 14585,
 3905,
 14566,
 5069,
 14528,
 3056,
 7573,
 8464,
 7771,
 17214,
 4459,
 10297,
 19626,
 12139,
 6948,
 12725,
 17985,
 7822,
 18863,
 18372,
 2519,
 16392,
 6780,
 9878,
 3642,
 12353,
 1166,
 19369,
 1341,
 6527,
 17529,
 2200,
 12017,
 15985,
 10558,
 15357,
 4433,
 5122,
 14595,
 7192,
 9751,
 3911,
 17824,
 8941,
 9282,
 6789,
 10790,
 1650,
 9919,
 3194,
 1392,
 3246,
 6796,
 12691,
 20091,
 20114,
 16665,
 7895,
 15727,
 7443,
 11223,
 12429,
 11880,
 11065,
 11233,
 19760,
 19341,
 14706,
 3831,
 18631,
 15089,
 4329,
 18501,
 1875,
 18035,
 14833,
 15888,
 19555,
 18449,
 7936,
 7292,
 14876,
 7973,
 1414,
 11013,
 9505,
 19722,
 6203,
 2178,
 15252,
 3203,
 2829,
 13974,
 6605,
 6125,
 2652,
 1311,
 12156,
 12880,
 2888,
 7120,
 13629,
 19134,
 10117,
 17435,
 12084,
 5502,
 14153,
 13138,
 6836,
 17607,
 7693,
 19682,
 17194,
 6577,
 3419,
 9208,
 12728,
 11609,
 14570,
 3384,
 12703,
 7165,
 12992,
 15232,
 12714,
 12615,
 686,
 14628,
 12034,
 1612,
 13696,
 15214,
 9476,
 5225,
 16830,
 7783,
 19652,
 11962,
 18947,
 18319,
 17771,
 18544,
 450,
 8882,
 4358,
 17854,
 4514,
 18159,
 13026,
 4060,
 11627,
 1651,
 12167,
 4258,
 5944,
 9917,
 19376,
 3217,
 17004,
 3202,
 4156,
 7281,
 9888,
 2132,
 6241,
 1301,
 16754,
 9753,
 16329,
 12122,
 11460,
 12445,
 18059,
 17205,
 2323,
 14342,
 10084,
 12721,
 11215,
 326,
 2859,
 15025,
 14547,
 846,
 9451,
 3292,
 12654,
 16400,
 19685,
 4409,
 19917,
 3216,
 8997,
 6214,
 13670,
 12877,
 18024,
 10214,
 10705,
 15932,
 11220,
 10841,
 6723,
 11909,
 18653,
 16982,
 2462,
 17362,
 13929,
 14458,
 19907,
 15969,
 4501,
 3059,
 12116,
 13263,
 6996,
 12927,
 18818,
 4058,
 16852,
 14368,
 19200,
 14258,
 3608,
 15879,
 18066,
 12306,
 19767,
 4174,
 19656,
 10306,
 6558,
 2805,
 16294,
 3691,
 16721,
 4316,
 16030,
 11757,
 16689,
 17568,
 7769,
 8171,
 3566,
 302,
 7303,
 4670,
 19210,
 8897,
 627,
 18331,
 4831,
 12252,
 14950,
 8808,
 1335,
 12468,
 19727,
 9355,
 11602,
 4438,
 14545,
 6630,
 4755,
 20142,
 9514,
 13857,
 1201,
 4250,
 4546,
 1836,
 1870,
 7349,
 16019,
 13321,
 12559,
 1554,
 13261,
 4804,
 13126,
 8105,
 5698,
 9028,
 19897,
 17643,
 11512,
 5584,
 3134,
 19340,
 8971,
 9307,
 19316,
 16846,
 12242,
 11213,
 14197,
 6945,
 3083,
 11319,
 10986,
 8365,
 975,
 5812,
 2434,
 1668,
 12533,
 14661,
 15682,
 2894,
 9655,
 10234,
 18570,
 7135,
 6988,
 8828,
 4951,
 12497,
 3504,
 9927,
 15845,
 15364,
 12191,
 19477,
 16372,
 16533,
 7595,
 2737,
 16177,
 3486,
 9098,
 5745,
 ...]

In [ ]:
from sklearn.model_selection import strai

In [105]:
train_idx

array([  246, 10159,  1249, ...,  1241,  1444,  3937])

In [46]:
adata.obs[adata.obs["doid_id"] == "DOID:1928"]["celltype"].unique()

['Williams Syndrome', 'Williams-Beuren Syndrome']
Categories (151, object): ['Acne Inversa', 'Acquired Immunodeficiency Syndrome', 'Acute Lymphoblastic Leukemia', 'Acute Myeloid Leukemia', ..., 'Type 2 Diabetes', 'Ulcerative Colitis', 'Williams Syndrome', 'Williams-Beuren Syndrome']

In [ ]:
adata.obs["celltype"]

In [107]:
idx_1 = np.argwhere(valid_obs["valid_split_1"].to_numpy() == 1)

In [109]:
idx_1.flatten()

array([  155,   156,   157, ..., 18618, 18619, 18620])

In [ ]:
rng = np.random.default_rng(42)
a = np.array([1, 2, 3, 4])
idx = rng.permutation(len(a))

In [112]:
(idx_1).shuffle()

AttributeError: 'numpy.ndarray' object has no attribute 'shuffle'