# Training with both RNA-Seq and Microarray data
We have seen that there is significant performance drop when training with both. Here we will go through all the filtering steps and evaluate how much data we have with different filtering thresholds.

In [31]:
import scanpy as sc
import sys
sys.path.append("../../")
from src.training import helpers as tr_h
adata = sc.read("/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-09-12-01/data.h5ad")

In [2]:
dict(adata.obs.groupby("dataset", observed=True)['celltype'].count()).items()

dict_items([('E-MEXP-3097', 5), ('E-MTAB-567', 27), ('E-MTAB-1030', 18), ('E-MTAB-1132', 489), ('E-MTAB-1516', 36), ('E-MTAB-1791', 192), ('E-MTAB-2312', 12), ('E-MTAB-2976', 8), ('E-MTAB-3338', 38), ('E-MTAB-3658', 8), ('E-MTAB-3664', 64), ('E-MTAB-3950', 98), ('E-MTAB-4054', 98), ('E-MTAB-4257', 34), ('E-MTAB-4586', 64), ('E-MTAB-4902', 8), ('E-MTAB-5385', 73), ('E-MTAB-5464', 66), ('E-MTAB-5616', 22), ('E-MTAB-5638', 39), ('E-MTAB-5678', 26), ('E-MTAB-6413', 21), ('E-MTAB-6490', 30), ('E-MTAB-7140', 7), ('E-MTAB-7145', 4), ('E-MTAB-7340', 15), ('E-MTAB-7406', 15), ('E-MTAB-7671', 7), ('E-MTAB-7860', 192), ('E-MTAB-7876', 57), ('E-MTAB-8448', 412), ('E-MTAB-8455', 45), ('E-MTAB-8887', 30), ('E-MTAB-9045', 20), ('E-MTAB-10190', 160), ('E-MTAB-10318', 70), ('E-MTAB-10604', 40), ('E-MTAB-10703', 134), ('E-MTAB-10916', 26), ('E-MTAB-11029', 9), ('E-MTAB-11240', 102), ('E-MTAB-11326', 107), ('E-MTAB-11415', 217), ('E-MTAB-11910', 40), ('E-MTAB-11919', 20), ('E-MTAB-12014', 20), ('E-MTAB-12184', 12), ('E-MTAB-12252', 10), ('E-MTAB-12309', 11), ('E-MTAB-12631', 36), ('GSE420', 8), ('GSE474', 24), ('GSE475', 7), ('GSE593', 10), ('GSE833', 15), ('GSE860', 33), ('GSE1010', 47), ('GSE1297', 98), ('GSE1299', 18), ('GSE1377', 4), ('GSE1420', 32), ('GSE1551', 23), ('GSE1650', 58), ('GSE1710', 21), ('GSE1719', 36), ('GSE1724', 24), ('GSE1739', 14), ('GSE1751', 45), ('GSE1767', 31), ('GSE1919', 20), ('GSE1987', 42), ('GSE2006', 11), ('GSE2052', 35), ('GSE2191', 58), ('GSE2503', 21), ('GSE2549', 45), ('GSE2657', 8), ('GSE2685', 30), ('GSE2724', 18), ('GSE2725', 10), ('GSE2738', 21), ('GSE3004', 10), ('GSE3112', 34), ('GSE3167', 50), ('GSE3185', 15), ('GSE3189', 52), ('GSE3268', 10), ('GSE3307', 381), ('GSE3325', 38), ('GSE3365', 68), ('GSE3410', 6), ('GSE3467', 18), ('GSE3585', 12), ('GSE3678', 14), ('GSE3744', 47), ('GSE3790', 404), ('GSE3860', 36), ('GSE3868', 29), ('GSE3964', 35), ('GSE4036', 28), ('GSE4107', 22), ('GSE4115', 187), ('GSE4172', 12), ('GSE4182', 9), ('GSE4183', 46), ('GSE4226', 28), ('GSE4229', 40), ('GSE4290', 149), ('GSE4302', 70), ('GSE4587', 17), ('GSE4588', 66), ('GSE4757', 20), ('GSE5058', 39), ('GSE5090', 49), ('GSE5108', 22), ('GSE5281', 161), ('GSE5364', 282), ('GSE5370', 9), ('GSE5388', 61), ('GSE5389', 21), ('GSE5390', 15), ('GSE5406', 226), ('GSE5550', 17), ('GSE5667', 12), ('GSE5764', 15), ('GSE5850', 12), ('GSE6004', 22), ('GSE6008', 115), ('GSE6011', 37), ('GSE6044', 44), ('GSE6054', 108), ('GSE6088', 36), ('GSE6222', 14), ('GSE6283', 21), ('GSE6338', 60), ('GSE6364', 37), ('GSE6475', 24), ('GSE6551', 5), ('GSE6613', 72), ('GSE6631', 44), ('GSE6691', 69), ('GSE6710', 77), ('GSE6731', 17), ('GSE6764', 251), ('GSE6791', 51), ('GSE6798', 29), ('GSE6955', 6), ('GSE6956', 89), ('GSE7014', 11), ('GSE7036', 6), ('GSE7116', 31), ('GSE7177', 12), ('GSE7178', 12), ('GSE7179', 12), ('GSE7305', 20), ('GSE7451', 20), ('GSE7476', 18), ('GSE7553', 58), ('GSE7586', 17), ('GSE7621', 25), ('GSE7670', 57), ('GSE7700', 10), ('GSE7803', 13), ('GSE7846', 10), ('GSE8050', 4), ('GSE8157', 23), ('GSE8397', 43), ('GSE8545', 36), ('GSE8607', 49), ('GSE8762', 44), ('GSE8835', 66), ('GSE8954', 14), ('GSE8977', 22), ('GSE9006', 282), ('GSE9348', 82), ('GSE9452', 28), ('GSE9476', 80), ('GSE9511', 11), ('GSE9574', 29), ('GSE9624', 11), ('GSE9686', 13), ('GSE9844', 38), ('GSE9861', 8), ('GSE9874', 57), ('GSE9877', 74), ('GSE10006', 51), ('GSE10064', 10), ('GSE10072', 105), ('GSE10161', 27), ('GSE10191', 31), ('GSE10325', 67), ('GSE10334', 494), ('GSE10500', 16), ('GSE10575', 8), ('GSE10586', 27), ('GSE10616', 73), ('GSE10650', 4), ('GSE10667', 61), ('GSE10714', 19), ('GSE10715', 30), ('GSE10746', 14), ('GSE10760', 196), ('GSE10774', 14), ('GSE10789', 6), ('GSE10799', 19), ('GSE10810', 58), ('GSE10921', 7), ('GSE10927', 43), ('GSE10946', 23), ('GSE10950', 48), ('GSE11083', 57), ('GSE11151', 61), ('GSE11196', 48), ('GSE11199', 8), ('GSE11393', 6), ('GSE11414', 8), ('GSE11501', 132), ('GSE11524', 60), ('GSE11675', 6), ('GSE11783', 22), ('GSE11784', 248), ('GSE11839', 12), ('GSE11886', 66), ('GSE11889', 47), ('GSE11906', 64), ('GSE11917', 5), ('GSE11967', 8), ('GSE11971', 23), ('GSE12021', 30), ('GSE12090', 18), ('GSE12102', 50), ('GSE12305', 6), ('GSE12368', 18), ('GSE12374', 17), ('GSE12484', 4), ('GSE12643', 20), ('GSE12644', 20), ('GSE12649', 205), ('GSE12654', 54), ('GSE12679', 38), ('GSE12685', 14), ('GSE12734', 14), ('GSE12767', 12), ('GSE12814', 44), ('GSE13083', 14), ('GSE13319', 77), ('GSE13355', 476), ('GSE13367', 149), ('GSE13396', 68), ('GSE13471', 8), ('GSE13507', 175), ('GSE13591', 152), ('GSE13760', 14), ('GSE13827', 4), ('GSE13849', 179), ('GSE13887', 46), ('GSE13896', 46), ('GSE13985', 10), ('GSE14001', 46), ('GSE14245', 48), ('GSE14297', 25), ('GSE14317', 26), ('GSE14323', 57), ('GSE14520', 64), ('GSE14577', 30), ('GSE14580', 30), ('GSE14882', 16), ('GSE14905', 169), ('GSE14924', 82), ('GSE14975', 20), ('GSE15061', 405), ('GSE15090', 40), ('GSE15209', 29), ('GSE15222', 363), ('GSE15471', 156), ('GSE15568', 29), ('GSE15573', 33), ('GSE15578', 21), ('GSE15605', 148), ('GSE15629', 24), ('GSE15641', 153), ('GSE15645', 136), ('GSE15773', 19), ('GSE15777', 31), ('GSE15823', 8), ('GSE15824', 93), ('GSE15932', 48), ('GSE16011', 284), ('GSE16032', 10), ('GSE16054', 12), ('GSE16120', 65), ('GSE16161', 18), ('GSE16238', 6), ('GSE16354', 24), ('GSE16355', 6), ('GSE16356', 6), ('GSE16443', 121), ('GSE16461', 16), ('GSE16464', 12), ('GSE16499', 30), ('GSE16515', 52), ('GSE16538', 12), ('GSE16677', 11), ('GSE16715', 17), ('GSE16728', 30), ('GSE16759', 8), ('GSE16969', 14), ('GSE16972', 10), ('GSE17048', 234), ('GSE17054', 13), ('GSE17114', 29), ('GSE17269', 7), ('GSE17393', 15), ('GSE17612', 51), ('GSE17635', 22), ('GSE17679', 62), ('GSE18090', 34), ('GSE18155', 16), ('GSE18309', 6), ('GSE18312', 38), ('GSE18462', 10), ('GSE18670', 36), ('GSE18781', 37), ('GSE18838', 28), ('GSE18842', 91), ('GSE18885', 172), ('GSE18920', 44), ('GSE18965', 16), ('GSE19187', 60), ('GSE19188', 286), ('GSE19205', 12), ('GSE19295', 8), ('GSE19314', 58), ('GSE19587', 22), ('GSE19728', 32), ('GSE19750', 48), ('GSE19826', 23), ('GSE20129', 119), ('GSE20141', 18), ('GSE20146', 19), ('GSE20153', 16), ('GSE20159', 33), ('GSE20163', 17), ('GSE20189', 161), ('GSE20257', 82), ('GSE20266', 20), ('GSE20347', 34), ('GSE20430', 29), ('GSE20436', 60), ('GSE20437', 42), ('GSE20571', 27), ('GSE20910', 49), ('GSE20916', 398), ('GSE20948', 28), ('GSE20966', 20), ('GSE21125', 36), ('GSE21354', 8), ('GSE21411', 29), ('GSE21422', 10), ('GSE21795', 6), ('GSE21899', 18), ('GSE21933', 42), ('GSE21935', 42), ('GSE21942', 29), ('GSE21959', 36), ('GSE22098', 146), ('GSE22356', 38), ('GSE22491', 18), ('GSE22528', 10), ('GSE22529', 104), ('GSE22544', 18), ('GSE22598', 34), ('GSE22619', 20), ('GSE22780', 16), ('GSE22840', 34), ('GSE22866', 46), ('GSE22889', 24), ('GSE23066', 9), ('GSE23075', 5), ('GSE23117', 29), ('GSE23203', 24), ('GSE23290', 18), ('GSE23293', 23), ('GSE23343', 17), ('GSE23361', 12), ('GSE23391', 8), ('GSE23400', 208), ('GSE23586', 6), ('GSE23676', 33), ('GSE23705', 56), ('GSE23746', 95), ('GSE23832', 12), ('GSE23910', 8), ('GSE23933', 6), ('GSE24100', 7), ('GSE24124', 139), ('GSE24129', 16), ('GSE24147', 42), ('GSE24171', 29), ('GSE24206', 56), ('GSE24250', 14), ('GSE24287', 52), ('GSE24378', 17), ('GSE24383', 56), ('GSE24395', 17), ('GSE24514', 49), ('GSE24519', 38), ('GSE24667', 23), ('GSE24706', 30), ('GSE24870', 43), ('GSE25101', 32), ('GSE25226', 56), ('GSE25401', 56), ('GSE25427', 34), ('GSE25429', 34), ('GSE25462', 23), ('GSE25487', 19), ('GSE25518', 23), ('GSE25624', 48), ('GSE25628', 28), ('GSE25638', 136), ('GSE25673', 24), ('GSE25906', 60), ('GSE26061', 22), ('GSE26125', 21), ('GSE26276', 6), ('GSE26294', 16), ('GSE26484', 14), ('GSE26712', 195), ('GSE26725', 17), ('GSE26886', 107), ('GSE26887', 17), ('GSE26910', 24), ('GSE26952', 23), ('GSE26969', 6), ('GSE26972', 6), ('GSE26975', 38), ('GSE26990', 8), ('GSE27011', 108), ('GSE27057', 10), ('GSE27058', 9), ('GSE27131', 21), ('GSE27155', 61), ('GSE27205', 12), ('GSE27206', 5), ('GSE27262', 50), ('GSE27276', 36), ('GSE27342', 160), ('GSE27356', 32), ('GSE27383', 101), ('GSE27427', 33), ('GSE27489', 40), ('GSE27536', 78), ('GSE27543', 16), ('GSE27562', 150), ('GSE27601', 26), ('GSE27651', 47), ('GSE27678', 31), ('GSE27838', 32), ('GSE27890', 4), ('GSE27915', 16), ('GSE27949', 23), ('GSE27993', 10), ('GSE28000', 126), ('GSE28042', 94), ('GSE28107', 12), ('GSE28192', 24), ('GSE28253', 22), ('GSE28345', 8), ('GSE28360', 14), ('GSE28405', 171), ('GSE28735', 90), ('GSE28863', 10), ('GSE28894', 114), ('GSE28945', 20), ('GSE29006', 4), ('GSE29044', 109), ('GSE29133', 6), ('GSE29142', 39), ('GSE29156', 59), ('GSE29220', 22), ('GSE29265', 40), ('GSE29330', 18), ('GSE29366', 67), ('GSE29377', 90), ('GSE29378', 63), ('GSE29429', 232), ('GSE29431', 66), ('GSE29746', 42), ('GSE29819', 50), ('GSE29927', 20), ('GSE30118', 7), ('GSE30134', 60), ('GSE30153', 26), ('GSE30174', 20), ('GSE30208', 63), ('GSE30209', 58), ('GSE30210', 247), ('GSE30292', 6), ('GSE30304', 18), ('GSE30522', 10), ('GSE30933', 148), ('GSE31014', 14), ('GSE31048', 203), ('GSE31095', 20), ('GSE31138', 6), ('GSE31139', 37), ('GSE31189', 92), ('GSE31243', 40), ('GSE31469', 18), ('GSE31470', 6), ('GSE31471', 30), ('GSE31474', 6), ('GSE31475', 6), ('GSE31547', 50), ('GSE31552', 36), ('GSE31757', 10), ('GSE31773', 80), ('GSE31821', 6), ('GSE31879', 14), ('GSE31934', 6), ('GSE32154', 4), ('GSE32175', 20), ('GSE32269', 55), ('GSE32299', 10), ('GSE32317', 19), ('GSE32323', 34), ('GSE32407', 60), ('GSE32488', 39), ('GSE32575', 30), ('GSE32645', 6), ('GSE32676', 32), ('GSE32915', 24), ('GSE32924', 46), ('GSE32988', 72), ('GSE33075', 19), ('GSE33111', 6), ('GSE33113', 96), ('GSE33126', 18), ('GSE33205', 69), ('GSE33223', 21), ('GSE33426', 71), ('GSE33463', 109), ('GSE33532', 100), ('GSE33566', 123), ('GSE33615', 88), ('GSE33630', 94), ('GSE33774', 15), ('GSE33855', 31), ('GSE33886', 7), ('GSE33943', 58), ('GSE34015', 10), ('GSE34111', 18), ('GSE34198', 145), ('GSE34201', 72), ('GSE34205', 50), ('GSE34248', 28), ('GSE34287', 63), ('GSE34465', 48), ('GSE34516', 14), ('GSE34526', 10), ('GSE34577', 120), ('GSE34608', 36), ('GSE34619', 18), ('GSE34861', 194), ('GSE34885', 14), ('GSE35007', 371), ('GSE35008', 28), ('GSE35010', 31), ('GSE35108', 15), ('GSE35133', 24), ('GSE35179', 10), ('GSE35287', 32), ('GSE35388', 8), ('GSE35487', 31), ('GSE35488', 31), ('GSE35493', 79), ('GSE35561', 6), ('GSE35574', 59), ('GSE35643', 12), ('GSE35665', 37), ('GSE35711', 44), ('GSE35713', 222), ('GSE35776', 24), ('GSE35956', 10), ('GSE35974', 181), ('GSE35977', 196), ('GSE36076', 33), ('GSE36295', 50), ('GSE36297', 16), ('GSE36398', 50), ('GSE36400', 14), ('GSE36474', 7), ('GSE36668', 8), ('GSE36701', 335), ('GSE36761', 29), ('GSE36765', 14), ('GSE36807', 22), ('GSE36895', 52), ('GSE36961', 145), ('GSE36980', 80), ('GSE37023', 216), ('GSE37120', 32), ('GSE37171', 115), ('GSE37258', 15), ('GSE37263', 16), ('GSE37264', 16), ('GSE37283', 25), ('GSE37307', 47), ('GSE37356', 66), ('GSE37460', 24), ('GSE37517', 12), ('GSE37573', 104), ('GSE37582', 121), ('GSE37750', 17), ('GSE37751', 108), ('GSE37768', 56), ('GSE37815', 24), ('GSE37911', 18), ('GSE37912', 109), ('GSE37981', 18), ('GSE37985', 6), ('GSE38010', 8), ('GSE38043', 6), ('GSE38153', 12), ('GSE38174', 132), ('GSE38226', 30), ('GSE38264', 38), ('GSE38267', 51), ('GSE38312', 10), ('GSE38351', 61), ('GSE38396', 8), ('GSE38417', 22), ('GSE38424', 8), ('GSE38481', 37), ('GSE38484', 202), ('GSE38543', 88), ('GSE38597', 8), ('GSE38642', 63), ('GSE38666', 45), ('GSE38713', 69), ('GSE38750', 34), ('GSE38751', 10), ('GSE38931', 8), ('GSE38958', 115), ('GSE38961', 6), ('GSE39041', 9), ('GSE39345', 52), ('GSE39388', 9), ('GSE39400', 39), ('GSE39411', 184), ('GSE39420', 28), ('GSE39454', 28), ('GSE39642', 34), ('GSE39645', 40), ('GSE39653', 32), ('GSE39683', 71), ('GSE39754', 176), ('GSE39791', 144), ('GSE39843', 12), ('GSE40012', 97), ('GSE40033', 11), ('GSE40102', 24), ('GSE40182', 39), ('GSE40184', 18), ('GSE40223', 10), ('GSE40263', 30), ('GSE40445', 10), ('GSE40568', 8), ('GSE40583', 24), ('GSE40595', 77), ('GSE40732', 194), ('GSE40791', 194), ('GSE40839', 18), ('GSE40888', 48), ('GSE40889', 153), ('GSE40911', 44), ('GSE41011', 31), ('GSE41030', 6), ('GSE41038', 13), ('GSE41258', 327), ('GSE41328', 20), ('GSE41386', 6), ('GSE41414', 11), ('GSE41649', 8), ('GSE41662', 48), ('GSE41663', 30), ('GSE41681', 4), ('GSE41687', 24), ('GSE41751', 4), ('GSE41848', 212), ('GSE41849', 102), ('GSE41861', 232), ('GSE41862', 116), ('GSE41863', 56), ('GSE41890', 92), ('GSE42057', 136), ('GSE42331', 65), ('GSE42492', 6), ('GSE42546', 91), ('GSE42568', 121), ('GSE42572', 12), ('GSE42632', 12), ('GSE42656', 87), ('GSE42677', 15), ('GSE42733', 15), ('GSE42764', 28), ('GSE42825', 34), ('GSE42826', 247), ('GSE42830', 147), ('GSE42832', 60), ('GSE42955', 17), ('GSE42956', 48), ('GSE42966', 15), ('GSE43017', 12), ('GSE43176', 108), ('GSE43264', 15), ('GSE43290', 51), ('GSE43292', 64), ('GSE43326', 6), ('GSE43458', 70), ('GSE43484', 6), ('GSE43488', 356), ('GSE43525', 30), ('GSE43591', 20), ('GSE43698', 26), ('GSE43754', 20), ('GSE43760', 24), ('GSE43924', 18), ('GSE43926', 13), ('GSE44037', 46), ('GSE44076', 688), ('GSE44077', 40), ('GSE44314', 22), ('GSE44426', 12), ('GSE44660', 25), ('GSE44711', 16), ('GSE44723', 18), ('GSE44874', 11), ('GSE44971', 44), ('GSE45050', 9), ('GSE45164', 13), ('GSE45188', 12), ('GSE45267', 87), ('GSE45291', 845), ('GSE45512', 10), ('GSE45516', 9), ('GSE45536', 40), ('GSE45570', 12), ('GSE45686', 40), ('GSE45709', 20), ('GSE45827', 170), ('GSE45923', 18), ('GSE46021', 20), ('GSE46053', 37), ('GSE46097', 378), ('GSE46171', 97), ('GSE46234', 12), ('GSE46239', 52), ('GSE46416', 42), ('GSE46449', 126), ('GSE46509', 16), ('GSE46517', 38), ('GSE46562', 19), ('GSE46570', 20), ('GSE46619', 9), ('GSE46687', 46), ('GSE46907', 20), ('GSE46960', 71), ('GSE47018', 18), ('GSE47197', 124), ('GSE47360', 6), ('GSE47460', 690), ('GSE47472', 22), ('GSE47552', 46), ('GSE47584', 10), ('GSE47598', 24), ('GSE47756', 186), ('GSE47908', 21), ('GSE47927', 94), ('GSE47944', 114), ('GSE47968', 41), ('GSE48051', 19), ('GSE48060', 52), ('GSE48072', 66), ('GSE48120', 10), ('GSE48129', 10), ('GSE48280', 19), ('GSE48350', 253), ('GSE48378', 27), ('GSE48424', 54), ('GSE48452', 28), ('GSE48521', 16), ('GSE48556', 139), ('GSE48634', 137), ('GSE48761', 24), ('GSE48812', 48), ('GSE48828', 24), ('GSE48958', 29), ('GSE48964', 6), ('GSE49036', 44), ('GSE49072', 145), ('GSE49126', 50), ('GSE49292', 9), ('GSE49454', 177), ('GSE49515', 33), ('GSE49524', 6), ('GSE49641', 36), ('GSE50006', 220), ('GSE50161', 75), ('GSE50195', 16), ('GSE50395', 6), ('GSE50484', 22), ('GSE50579', 112), ('GSE50627', 21), ('GSE50635', 65), ('GSE50738', 30), ('GSE50772', 81), ('GSE50790', 8), ('GSE50892', 17), ('GSE50901', 8), ('GSE51021', 28), ('GSE51024', 96), ('GSE51041', 5), ('GSE51092', 222), ('GSE51257', 6), ('GSE51392', 48), ('GSE51401', 48), ('GSE51404', 74), ('GSE51405', 107), ('GSE51490', 18), ('GSE51575', 78), ('GSE51799', 98), ('GSE51808', 74), ('GSE51843', 11), ('GSE51922', 18), ('GSE51981', 148), ('GSE51997', 25), ('GSE52037', 20), ('GSE52042', 8), ('GSE52130', 23), ('GSE52139', 16), ('GSE52202', 8), ('GSE52249', 7), ('GSE52463', 15), ('GSE52471', 31), ('GSE52519', 12), ('GSE52742', 6), ('GSE52752', 65), ('GSE52946', 30), ('GSE53000', 59), ('GSE53146', 10), ('GSE53157', 36), ('GSE53239', 9), ('GSE53257', 11), ('GSE53306', 52), ('GSE53419', 17), ('GSE53431', 24), ('GSE53441', 34), ('GSE53552', 49), ('GSE53697', 17), ('GSE53757', 120), ('GSE53795', 24), ('GSE53987', 210), ('GSE54002', 433), ('GSE54129', 132), ('GSE54248', 8), ('GSE54388', 22), ('GSE54400', 47), ('GSE54456', 169), ('GSE54495', 30), ('GSE54536', 10), ('GSE54644', 126), ('GSE54873', 14), ('GSE54934', 25), ('GSE54958', 37), ('GSE55092', 140), ('GSE55098', 22), ('GSE55201', 74), ('GSE55235', 40), ('GSE55276', 234), ('GSE55277', 234), ('GSE55288', 89), ('GSE55447', 156), ('GSE55457', 43), ('GSE55597', 32), ('GSE55650', 23), ('GSE55664', 45), ('GSE55909', 14), ('GSE55939', 4), ('GSE55945', 21), ('GSE55962', 66), ('GSE55976', 47), ('GSE56088', 24), ('GSE56481', 18), ('GSE56495', 12), ('GSE56500', 18), ('GSE56649', 22), ('GSE56766', 199), ('GSE56767', 218), ('GSE56787', 33), ('GSE56998', 16), ('GSE57130', 48), ('GSE57148', 162), ('GSE57183', 6), ('GSE57218', 40), ('GSE57338', 449), ('GSE57344', 4), ('GSE57383', 88), ('GSE57405', 88), ('GSE57475', 142), ('GSE57560', 16), ('GSE57691', 69), ('GSE57957', 78), ('GSE58058', 7), ('GSE58067', 12), ('GSE58178', 12), ('GSE58208', 32), ('GSE58331', 83), ('GSE58435', 10), ('GSE58539', 17), ('GSE58545', 62), ('GSE58640', 15), ('GSE58933', 10), ('GSE59019', 25), ('GSE59034', 32), ('GSE59051', 5), ('GSE59259', 16), ('GSE59312', 79), ('GSE59363', 42), ('GSE60052', 86), ('GSE60403', 16), ('GSE60502', 36), ('GSE60542', 58), ('GSE60601', 8), ('GSE60709', 45), ('GSE60762', 8), ('GSE61019', 7), ('GSE61120', 20), ('GSE61141', 24), ('GSE61203', 48), ('GSE61304', 60), ('GSE61399', 29), ('GSE61405', 19), ('GSE61635', 129), ('GSE61651', 65), ('GSE62019', 6), ('GSE62165', 157), ('GSE62232', 91), ('GSE62333', 40), ('GSE62430', 24), ('GSE62452', 126), ('GSE62642', 14), ('GSE62764', 8), ('GSE62932', 80), ('GSE63040', 16), ('GSE63055', 7), ('GSE63085', 41), ('GSE63214', 24), ('GSE63357', 26), ('GSE63379', 67), ('GSE63383', 6), ('GSE63425', 8), ('GSE63571', 14), ('GSE63744', 14), ('GSE63941', 12), ('GSE64003', 18), ('GSE64034', 16), ('GSE64041', 185), ('GSE64392', 37), ('GSE64486', 11), ('GSE64801', 14), ('GSE64810', 69), ('GSE64814', 94), ('GSE64912', 22), ('GSE64913', 70), ('GSE64951', 94), ('GSE64998', 29), ('GSE65010', 48), ('GSE65055', 21), ('GSE65114', 28), ('GSE65127', 20), ('GSE65204', 69), ('GSE65409', 38), ('GSE65517', 7), ('GSE65635', 12), ('GSE65705', 34), ('GSE66117', 50), ('GSE66196', 8), ('GSE66229', 400), ('GSE66270', 28), ('GSE66271', 26), ('GSE66273', 11), ('GSE66354', 240), ('GSE66359', 13), ('GSE66360', 99), ('GSE66387', 18), ('GSE66407', 243), ('GSE66476', 10), ('GSE66573', 14), ('GSE66763', 16), ('GSE66988', 24), ('GSE67067', 6), ('GSE67333', 8), ('GSE67472', 148), ('GSE67527', 8), ('GSE67640', 24), ('GSE67764', 12), ('GSE67801', 18), ('GSE67812', 6), ('GSE67853', 27), ('GSE67939', 17), ('GSE67945', 6), ('GSE68004', 144), ('GSE68015', 256), ('GSE68316', 12), ('GSE68417', 57), ('GSE68605', 11), ('GSE68607', 84), ('GSE68689', 21), ('GSE68741', 16), ('GSE68849', 10), ('GSE68925', 7), ('GSE69175', 4), ('GSE69197', 6), ('GSE69210', 20), ('GSE69223', 30), ('GSE69252', 26), ('GSE69391', 18), ('GSE69428', 20), ('GSE69486', 12), ('GSE69549', 74), ('GSE69597', 64), ('GSE69601', 6), ('GSE69683', 672), ('GSE69732', 6), ('GSE69988', 6), ('GSE70468', 28), ('GSE70752', 32), ('GSE70818', 8), ('GSE70866', 23), ('GSE70955', 6), ('GSE71010', 58), ('GSE71053', 18), ('GSE71192', 8), ('GSE71220', 617), ('GSE71363', 18), ('GSE71370', 34), ('GSE71449', 23), ('GSE71613', 6), ('GSE71664', 24), ('GSE71709', 4), ('GSE71730', 25), ('GSE71799', 134), ('GSE71935', 26), ('GSE71989', 21), ('GSE72073', 8), ('GSE72213', 32), ('GSE72220', 204), ('GSE72267', 59), ('GSE72269', 5), ('GSE72304', 24), ('GSE72326', 223), ('GSE72377', 165), ('GSE72509', 153), ('GSE72625', 81), ('GSE72702', 30), ('GSE72748', 6), ('GSE72874', 65), ('GSE72920', 30), ('GSE72922', 23), ('GSE72999', 26), ('GSE73078', 20), ('GSE73129', 115), ('GSE73394', 46), ('GSE73395', 57), ('GSE73402', 82), ('GSE73461', 132), ('GSE73482', 190), ('GSE73613', 4), ('GSE73622', 50), ('GSE73655', 27), ('GSE73754', 92), ('GSE73953', 27), ('GSE73968', 12), ('GSE74075', 16), ('GSE74123', 8), ('GSE74144', 44), ('GSE74358', 28), ('GSE74369', 32), ('GSE74604', 60), ('GSE74629', 50), ('GSE74697', 34), ('GSE74761', 11), ('GSE74986', 98), ('GSE75023', 27), ('GSE75091', 24), ('GSE75214', 119), ('GSE75271', 55), ('GSE75303', 12), ('GSE75436', 30), ('GSE75538', 28), ('GSE75539', 15), ('GSE75672', 21), ('GSE75699', 8), ('GSE75793', 12), ('GSE75852', 12), ('GSE75890', 47), ('GSE75916', 

In [ ]:
# drop duplicates
adata.obs["celltype"] = adata.obs["doid_id"]
adata.obs["sample_id"] = [x.split(".")[1] for x in adata.obs["ids"]]
print(adata.shape)
adata_drop = adata[~adata.obs.duplicated(subset=['sample_id','celltype'])]
print(adata_drop.shape)

# drop duplicate samples
adata.obs[~adata.obs.duplicated('sample_id', keep='first')]

(121142, 20608)
(100543, 20608)

NameError: name 'X_log1p' is not defined

In [115]:
adata_drop.shape

(100451, 20608)

In [116]:
adata_drop.obs.duplicated(subset=['sample_id']).sum()

1611

In [114]:
adata_drop.obs.groupby("sample_id")["celltype"]

Removed samples in multiple datasets, new shape: (100451, 20608)
Removed duplicate samples, new shape: (100451, 20608)

In [ ]:

adata_drop.obs[adata_drop.obs["dataset"] == "GSE20257"]["sample_id"].to_list()

['GSM101107', 'GSM364037']

In [73]:
adata_drop.obs[adata_drop.obs["dataset"] == "GSE20257"]

,ids,dataset,dataset_id,batch,batch_id,dsaid,tissue,n_genes,disease,celltype,disease_study,library,doid_study,doid_id,do_id,doid_disease,sample_id
65797,DSA05794.GSM101107.Control,GSE20257,GSE20257,1356,1356,DSA05794,Epithelium,17046,Control,Control,Chronic Obstructive Pulmonary Disease,Microarray,D,Control,Control,Control,GSM101107
65858,DSA05794.GSM364037.Case,GSE20257,GSE20257,1356,1356,DSA05794,Epithelium,17046,Chronic Obstructive Pulmonary Disease,DOID:3083,Chronic Obstructive Pulmonary Disease,Microarray,D,DOID:3083,DOID:3083,chronic obstructive pulmonary disease,GSM364037

In [37]:
adata_drop.obs.groupby("dataset", observed=True)['celltype'].count()

dataset
E-MEXP-3097       5
E-MTAB-567       27
E-MTAB-1030      18
E-MTAB-1132     243
E-MTAB-1516      36
               ...
TCGA-LUSC       550
TCGA-PAAD       182
TCGA-PRAD       551
TCGA-STAD       407
TCGA-THCA      1067
Name: celltype, Length: 2136, dtype: int64

In [ ]:
adata_drop_dis = adata_drop[adata_drop.obs['disease'] != 'Control']

In [98]:
pair_counts[pair_counts<2]

celltype   dataset
DOID:3083  GSE20257    1
Name: n, dtype: int64

In [101]:
pair_counts = (
        adata.obs.groupby(["celltype", "dataset"], observed=True)
                .size()
                .rename("n")
    )
_datasets_control_passed = pair_counts[pair_counts >= 2].index

['E-MEXP-3097',
 'E-MTAB-567',
 'E-MTAB-1030',
 'E-MTAB-1132',
 'E-MTAB-1516',
 'E-MTAB-1791',
 'E-MTAB-2312',
 'E-MTAB-2976',
 'E-MTAB-3338',
 'E-MTAB-3658',
 'E-MTAB-3664',
 'E-MTAB-3950',
 'E-MTAB-4054',
 'E-MTAB-4257',
 'E-MTAB-4586',
 'E-MTAB-4902',
 'E-MTAB-5385',
 'E-MTAB-5464',
 'E-MTAB-5616',
 'E-MTAB-5638',
 'E-MTAB-5678',
 'E-MTAB-6413',
 'E-MTAB-6490',
 'E-MTAB-7140',
 'E-MTAB-7145',
 'E-MTAB-7340',
 'E-MTAB-7406',
 'E-MTAB-7671',
 'E-MTAB-7860',
 'E-MTAB-7876',
 'E-MTAB-8448',
 'E-MTAB-8455',
 'E-MTAB-8887',
 'E-MTAB-9045',
 'E-MTAB-10190',
 'E-MTAB-10318',
 'E-MTAB-10604',
 'E-MTAB-10703',
 'E-MTAB-10916',
 'E-MTAB-11029',
 'E-MTAB-11240',
 'E-MTAB-11326',
 'E-MTAB-11415',
 'E-MTAB-11910',
 'E-MTAB-11919',
 'E-MTAB-12014',
 'E-MTAB-12184',
 'E-MTAB-12252',
 'E-MTAB-12309',
 'E-MTAB-12631',
 'GSE420',
 'GSE474',
 'GSE475',
 'GSE593',
 'GSE833',
 'GSE860',
 'GSE1010',
 'GSE1297',
 'GSE1299',
 'GSE1377',
 'GSE1420',
 'GSE1551',
 'GSE1650',
 'GSE1710',
 'GSE1719',
 'GSE1724',
 'GSE1739',
 'GSE1751',
 'GSE1767',
 'GSE1919',
 'GSE1987',
 'GSE2006',
 'GSE2052',
 'GSE2191',
 'GSE2503',
 'GSE2549',
 'GSE2657',
 'GSE2685',
 'GSE2724',
 'GSE2725',
 'GSE2738',
 'GSE3004',
 'GSE3112',
 'GSE3167',
 'GSE3185',
 'GSE3189',
 'GSE3268',
 'GSE3307',
 'GSE3325',
 'GSE3365',
 'GSE3410',
 'GSE3467',
 'GSE3585',
 'GSE3678',
 'GSE3744',
 'GSE3790',
 'GSE3860',
 'GSE3868',
 'GSE3964',
 'GSE4036',
 'GSE4107',
 'GSE4115',
 'GSE4172',
 'GSE4182',
 'GSE4183',
 'GSE4226',
 'GSE4229',
 'GSE4290',
 'GSE4302',
 'GSE4587',
 'GSE4588',
 'GSE4757',
 'GSE5058',
 'GSE5090',
 'GSE5108',
 'GSE5281',
 'GSE5364',
 'GSE5370',
 'GSE5388',
 'GSE5389',
 'GSE5390',
 'GSE5406',
 'GSE5550',
 'GSE5667',
 'GSE5764',
 'GSE5850',
 'GSE6004',
 'GSE6008',
 'GSE6011',
 'GSE6044',
 'GSE6054',
 'GSE6088',
 'GSE6222',
 'GSE6283',
 'GSE6338',
 'GSE6364',
 'GSE6475',
 'GSE6551',
 'GSE6613',
 'GSE6631',
 'GSE6691',
 'GSE6710',
 'GSE6731',
 'GSE6764',
 'GSE6791',
 'GSE6798',
 'GSE6955',
 'GSE6956',
 'GSE7014',
 'GSE7036',
 'GSE7116',
 'GSE7177',
 'GSE7178',
 'GSE7179',
 'GSE7305',
 'GSE7451',
 'GSE7476',
 'GSE7553',
 'GSE7586',
 'GSE7621',
 'GSE7670',
 'GSE7700',
 'GSE7803',
 'GSE7846',
 'GSE8050',
 'GSE8157',
 'GSE8397',
 'GSE8545',
 'GSE8607',
 'GSE8762',
 'GSE8835',
 'GSE8954',
 'GSE8977',
 'GSE9006',
 'GSE9348',
 'GSE9452',
 'GSE9476',
 'GSE9511',
 'GSE9574',
 'GSE9624',
 'GSE9686',
 'GSE9844',
 'GSE9861',
 'GSE9874',
 'GSE9877',
 'GSE10006',
 'GSE10064',
 'GSE10072',
 'GSE10161',
 'GSE10191',
 'GSE10325',
 'GSE10334',
 'GSE10500',
 'GSE10575',
 'GSE10586',
 'GSE10616',
 'GSE10650',
 'GSE10667',
 'GSE10714',
 'GSE10715',
 'GSE10746',
 'GSE10760',
 'GSE10774',
 'GSE10789',
 'GSE10799',
 'GSE10810',
 'GSE10921',
 'GSE10927',
 'GSE10946',
 'GSE10950',
 'GSE11083',
 'GSE11151',
 'GSE11196',
 'GSE11199',
 'GSE11393',
 'GSE11414',
 'GSE11501',
 'GSE11524',
 'GSE11675',
 'GSE11783',
 'GSE11784',
 'GSE11839',
 'GSE11886',
 'GSE11889',
 'GSE11906',
 'GSE11917',
 'GSE11967',
 'GSE11971',
 'GSE12021',
 'GSE12090',
 'GSE12102',
 'GSE12305',
 'GSE12368',
 'GSE12374',
 'GSE12484',
 'GSE12643',
 'GSE12644',
 'GSE12649',
 'GSE12654',
 'GSE12679',
 'GSE12685',
 'GSE12734',
 'GSE12767',
 'GSE12814',
 'GSE13083',
 'GSE13319',
 'GSE13355',
 'GSE13367',
 'GSE13396',
 'GSE13471',
 'GSE13507',
 'GSE13591',
 'GSE13760',
 'GSE13827',
 'GSE13849',
 'GSE13887',
 'GSE13896',
 'GSE13985',
 'GSE14001',
 'GSE14245',
 'GSE14297',
 'GSE14317',
 'GSE14323',
 'GSE14520',
 'GSE14577',
 'GSE14580',
 'GSE14882',
 'GSE14905',
 'GSE14924',
 'GSE14975',
 'GSE15061',
 'GSE15090',
 'GSE15209',
 'GSE15222',
 'GSE15471',
 'GSE15568',
 'GSE15573',
 'GSE15578',
 'GSE15605',
 'GSE15629',
 'GSE15641',
 'GSE15645',
 'GSE15773',
 'GSE15777',
 'GSE15823',
 'GSE15824',
 'GSE15932',
 'GSE16011',
 'GSE16032',
 'GSE16054',
 'GSE16120',
 'GSE16161',
 'GSE16238',
 'GSE16354',
 'GSE16355',
 'GSE16356',
 'GSE16443',
 'GSE16461',
 'GSE16464',
 'GSE16499',
 'GSE16515',
 'GSE16538',
 'GSE16677',
 'GSE16715',
 'GSE16728',
 'GSE16759',
 'GSE16969',
 'GSE16972',
 'GSE17048',
 'GSE17054',
 'GSE17114',
 'GSE17269',
 'GSE17393',
 'GSE17612',
 'GSE17635',
 'GSE17679',
 'GSE18090',
 'GSE18155',
 'GSE18309',
 'GSE18312',
 'GSE18462',
 'GSE18670',
 'GSE18781',
 'GSE18838',
 'GSE18842',
 'GSE18885',
 'GSE18920',
 'GSE18965',
 'GSE19187',
 'GSE19188',
 'GSE19205',
 'GSE19295',
 'GSE19314',
 'GSE19587',
 'GSE19728',
 'GSE19750',
 'GSE19826',
 'GSE20129',
 'GSE20141',
 'GSE20146',
 'GSE20153',
 'GSE20159',
 'GSE20163',
 'GSE20189',
 'GSE20257',
 'GSE20266',
 'GSE20347',
 'GSE20430',
 'GSE20436',
 'GSE20437',
 'GSE20571',
 'GSE20910',
 'GSE20916',
 'GSE20948',
 'GSE20966',
 'GSE21125',
 'GSE21354',
 'GSE21411',
 'GSE21422',
 'GSE21795',
 'GSE21899',
 'GSE21933',
 'GSE21935',
 'GSE21942',
 'GSE21959',
 'GSE22098',
 'GSE22356',
 'GSE22491',
 'GSE22528',
 'GSE22529',
 'GSE22544',
 'GSE22598',
 'GSE22619',
 'GSE22780',
 'GSE22840',
 'GSE22866',
 'GSE22889',
 'GSE23066',
 'GSE23075',
 'GSE23117',
 'GSE23203',
 'GSE23290',
 'GSE23293',
 'GSE23343',
 'GSE23361',
 'GSE23391',
 'GSE23400',
 'GSE23586',
 'GSE23676',
 'GSE23705',
 'GSE23746',
 'GSE23832',
 'GSE23910',
 'GSE23933',
 'GSE24100',
 'GSE24124',
 'GSE24129',
 'GSE24147',
 'GSE24171',
 'GSE24206',
 'GSE24250',
 'GSE24287',
 'GSE24378',
 'GSE24383',
 'GSE24395',
 'GSE24514',
 'GSE24519',
 'GSE24667',
 'GSE24706',
 'GSE24870',
 'GSE25101',
 'GSE25226',
 'GSE25401',
 'GSE25427',
 'GSE25429',
 'GSE25462',
 'GSE25487',
 'GSE25518',
 'GSE25624',
 'GSE25628',
 'GSE25638',
 'GSE25673',
 'GSE25906',
 'GSE26061',
 'GSE26125',
 'GSE26276',
 'GSE26294',
 'GSE26484',
 'GSE26712',
 'GSE26725',
 'GSE26886',
 'GSE26887',
 'GSE26910',
 'GSE26952',
 'GSE26969',
 'GSE26972',
 'GSE26975',
 'GSE26990',
 'GSE27011',
 'GSE27057',
 'GSE27058',
 'GSE27131',
 'GSE27155',
 'GSE27205',
 'GSE27206',
 'GSE27262',
 'GSE27276',
 'GSE27342',
 'GSE27356',
 'GSE27383',
 'GSE27427',
 'GSE27489',
 'GSE27536',
 'GSE27543',
 'GSE27562',
 'GSE27601',
 'GSE27651',
 'GSE27678',
 'GSE27838',
 'GSE27890',
 'GSE27915',
 'GSE27949',
 'GSE27993',
 'GSE28000',
 'GSE28042',
 'GSE28107',
 'GSE28192',
 'GSE28253',
 'GSE28345',
 'GSE28360',
 'GSE28405',
 'GSE28735',
 'GSE28863',
 'GSE28894',
 'GSE28945',
 'GSE29006',
 'GSE29044',
 'GSE29133',
 'GSE29142',
 'GSE29156',
 'GSE29220',
 'GSE29265',
 'GSE29330',
 'GSE29366',
 'GSE29377',
 'GSE29378',
 'GSE29429',
 'GSE29431',
 'GSE29746',
 'GSE29819',
 'GSE29927',
 'GSE30118',
 'GSE30134',
 'GSE30153',
 'GSE30174',
 'GSE30208',
 'GSE30209',
 'GSE30210',
 'GSE30292',
 'GSE30304',
 'GSE30522',
 'GSE30933',
 'GSE31014',
 'GSE31048',
 'GSE31095',
 'GSE31138',
 'GSE31139',
 'GSE31189',
 'GSE31243',
 'GSE31469',
 'GSE31470',
 'GSE31471',
 'GSE31474',
 'GSE31475',
 'GSE31547',
 'GSE31552',
 'GSE31757',
 'GSE31773',
 'GSE31821',
 'GSE31879',
 'GSE31934',
 'GSE32154',
 'GSE32175',
 'GSE32269',
 'GSE32299',
 'GSE32317',
 'GSE32323',
 'GSE32407',
 'GSE32488',
 'GSE32575',
 'GSE32645',
 'GSE32676',
 'GSE32915',
 'GSE32924',
 'GSE32988',
 'GSE33075',
 'GSE33111',
 'GSE33113',
 'GSE33126',
 'GSE33205',
 'GSE33223',
 'GSE33426',
 'GSE33463',
 'GSE33532',
 'GSE33566',
 'GSE33615',
 'GSE33630',
 'GSE33774',
 'GSE33855',
 'GSE33886',
 'GSE33943',
 'GSE34015',
 'GSE34111',
 'GSE34198',
 'GSE34201',
 'GSE34205',
 'GSE34248',
 'GSE34287',
 'GSE34465',
 'GSE34516',
 'GSE34526',
 'GSE34577',
 'GSE34608',
 'GSE34619',
 'GSE34861',
 'GSE34885',
 'GSE35007',
 'GSE35008',
 'GSE35010',
 'GSE35108',
 'GSE35133',
 'GSE35179',
 'GSE35287',
 'GSE35388',
 'GSE35487',
 'GSE35488',
 'GSE35493',
 'GSE35561',
 'GSE35574',
 'GSE35643',
 'GSE35665',
 'GSE35711',
 'GSE35713',
 'GSE35776',
 'GSE35956',
 'GSE35974',
 'GSE35977',
 'GSE36076',
 'GSE36295',
 'GSE36297',
 'GSE36398',
 'GSE36400',
 'GSE36474',
 'GSE36668',
 'GSE36701',
 'GSE36761',
 'GSE36765',
 'GSE36807',
 'GSE36895',
 'GSE36961',
 'GSE36980',
 'GSE37023',
 'GSE37120',
 'GSE37171',
 'GSE37258',
 'GSE37263',
 'GSE37264',
 'GSE37283',
 'GSE37307',
 'GSE37356',
 'GSE37460',
 'GSE37517',
 'GSE37573',
 'GSE37582',
 'GSE37750',
 'GSE37751',
 'GSE37768',
 'GSE37815',
 'GSE37911',
 'GSE37912',
 'GSE37981',
 'GSE37985',
 'GSE38010',
 'GSE38043',
 'GSE38153',
 'GSE38174',
 'GSE38226',
 'GSE38264',
 'GSE38267',
 'GSE38312',
 'GSE38351',
 'GSE38396',
 'GSE38417',
 'GSE38424',
 'GSE38481',
 'GSE38484',
 'GSE38543',
 'GSE38597',
 'GSE38642',
 'GSE38666',
 'GSE38713',
 'GSE38750',
 'GSE38751',
 'GSE38931',
 'GSE38958',
 'GSE38961',
 'GSE39041',
 'GSE39345',
 'GSE39388',
 'GSE39400',
 'GSE39411',
 'GSE39420',
 'GSE39454',
 'GSE39642',
 'GSE39645',
 'GSE39653',
 'GSE39683',
 'GSE39754',
 'GSE39791',
 'GSE39843',
 'GSE40012',
 'GSE40033',
 'GSE40102',
 'GSE40182',
 'GSE40184',
 'GSE40223',
 'GSE40263',
 'GSE40445',
 'GSE40568',
 'GSE40583',
 'GSE40595',
 'GSE40732',
 'GSE40791',
 'GSE40839',
 'GSE40888',
 'GSE40889',
 'GSE40911',
 'GSE41011',
 'GSE41030',
 'GSE41038',
 'GSE41258',
 'GSE41328',
 'GSE41386',
 'GSE41414',
 'GSE41649',
 'GSE41662',
 'GSE41663',
 'GSE41681',
 'GSE41687',
 'GSE41751',
 'GSE41848',
 'GSE41849',
 'GSE41861',
 'GSE41862',
 'GSE41863',
 'GSE41890',
 'GSE42057',
 'GSE42331',
 'GSE42492',
 'GSE42546',
 'GSE42568',
 'GSE42572',
 'GSE42632',
 'GSE42656',
 'GSE42677',
 'GSE42733',
 'GSE42764',
 'GSE42825',
 'GSE42826',
 'GSE42830',
 'GSE42832',
 'GSE42955',
 'GSE42956',
 'GSE42966',
 'GSE43017',
 'GSE43176',
 'GSE43264',
 'GSE43290',
 'GSE43292',
 'GSE43326',
 'GSE43458',
 'GSE43484',
 'GSE43488',
 'GSE43525',
 'GSE43591',
 'GSE43698',
 'GSE43754',
 'GSE43760',
 'GSE43924',
 'GSE43926',
 'GSE44037',
 'GSE44076',
 'GSE44077',
 'GSE44314',
 'GSE44426',
 'GSE44660',
 'GSE44711',
 'GSE44723',
 'GSE44874',
 'GSE44971',
 'GSE45050',
 'GSE45164',
 'GSE45188',
 'GSE45267',
 'GSE45291',
 'GSE45512',
 'GSE45516',
 'GSE45536',
 'GSE45570',
 'GSE45686',
 'GSE45709',
 'GSE45827',
 'GSE45923',
 'GSE46021',
 'GSE46053',
 'GSE46097',
 'GSE46171',
 'GSE46234',
 'GSE46239',
 'GSE46416',
 'GSE46449',
 'GSE46509',
 'GSE46517',
 'GSE46562',
 'GSE46570',
 'GSE46619',
 'GSE46687',
 'GSE46907',
 'GSE46960',
 'GSE47018',
 'GSE47197',
 'GSE47360',
 'GSE47460',
 'GSE47472',
 'GSE47552',
 'GSE47584',
 'GSE47598',
 'GSE47756',
 'GSE47908',
 'GSE47927',
 'GSE47944',
 'GSE47968',
 'GSE48051',
 'GSE48060',
 'GSE48072',
 'GSE48120',
 'GSE48129',
 'GSE48280',
 'GSE48350',
 'GSE48378',
 'GSE48424',
 'GSE48452',
 'GSE48521',
 'GSE48556',
 'GSE48634',
 'GSE48761',
 'GSE48812',
 'GSE48828',
 'GSE48958',
 'GSE48964',
 'GSE49036',
 'GSE49072',
 'GSE49126',
 'GSE49292',
 'GSE49454',
 'GSE49515',
 'GSE49524',
 'GSE49641',
 'GSE50006',
 'GSE50161',
 'GSE50195',
 'GSE50395',
 'GSE50484',
 'GSE50579',
 'GSE50627',
 'GSE50635',
 'GSE50738',
 'GSE50772',
 'GSE50790',
 'GSE50892',
 'GSE50901',
 'GSE51021',
 'GSE51024',
 'GSE51041',
 'GSE51092',
 'GSE51257',
 'GSE51392',
 'GSE51401',
 'GSE51404',
 'GSE51405',
 'GSE51490',
 'GSE51575',
 'GSE51799',
 'GSE51808',
 'GSE51843',
 'GSE51922',
 'GSE51981',
 'GSE51997',
 'GSE52037',
 'GSE52042',
 'GSE52130',
 'GSE52139',
 'GSE52202',
 'GSE52249',
 'GSE52463',
 'GSE52471',
 'GSE52519',
 'GSE52742',
 'GSE52752',
 'GSE52946',
 'GSE53000',
 'GSE53146',
 'GSE53157',
 'GSE53239',
 'GSE53257',
 'GSE53306',
 'GSE53419',
 'GSE53431',
 'GSE53441',
 'GSE53552',
 'GSE53697',
 'GSE53757',
 'GSE53795',
 'GSE53987',
 'GSE54002',
 'GSE54129',
 'GSE54248',
 'GSE54388',
 'GSE54400',
 'GSE54456',
 'GSE54495',
 'GSE54536',
 'GSE54644',
 'GSE54873',
 'GSE54934',
 'GSE54958',
 'GSE55092',
 'GSE55098',
 'GSE55201',
 'GSE55235',
 'GSE55276',
 'GSE55277',
 'GSE55288',
 'GSE55447',
 'GSE55457',
 'GSE55597',
 'GSE55650',
 'GSE55664',
 'GSE55909',
 'GSE55939',
 'GSE55945',
 'GSE55962',
 'GSE55976',
 'GSE56088',
 'GSE56481',
 'GSE56495',
 'GSE56500',
 'GSE56649',
 'GSE56766',
 'GSE56767',
 'GSE56787',
 'GSE56998',
 'GSE57130',
 'GSE57148',
 'GSE57183',
 'GSE57218',
 'GSE57338',
 'GSE57344',
 'GSE57383',
 'GSE57405',
 'GSE57475',
 'GSE57560',
 'GSE57691',
 'GSE57957',
 'GSE58058',
 'GSE58067',
 'GSE58178',
 'GSE58208',
 'GSE58331',
 'GSE58435',
 'GSE58539',
 'GSE58545',
 'GSE58640',
 'GSE58933',
 'GSE59019',
 'GSE59034',
 'GSE59051',
 'GSE59259',
 'GSE59312',
 'GSE59363',
 'GSE60052',
 'GSE60403',
 'GSE60502',
 'GSE60542',
 'GSE60601',
 'GSE60709',
 'GSE60762',
 'GSE61019',
 'GSE61120',
 'GSE61141',
 'GSE61203',
 'GSE61304',
 'GSE61399',
 'GSE61405',
 'GSE61635',
 'GSE61651',
 'GSE62019',
 'GSE62165',
 'GSE62232',
 'GSE62333',
 'GSE62430',
 'GSE62452',
 'GSE62642',
 'GSE62764',
 'GSE62932',
 'GSE63040',
 'GSE63055',
 'GSE63085',
 'GSE63214',
 'GSE63357',
 'GSE63379',
 'GSE63383',
 'GSE63425',
 'GSE63571',
 'GSE63744',
 'GSE63941',
 'GSE64003',
 'GSE64034',
 'GSE64041',
 'GSE64392',
 'GSE64486',
 'GSE64801',
 'GSE64810',
 'GSE64814',
 'GSE64912',
 'GSE64913',
 'GSE64951',
 'GSE64998',
 'GSE65010',
 'GSE65055',
 'GSE65114',
 'GSE65127',
 'GSE65204',
 'GSE65409',
 'GSE65517',
 'GSE65635',
 'GSE65705',
 'GSE66117',
 'GSE66196',
 'GSE66229',
 'GSE66270',
 'GSE66271',
 'GSE66273',
 'GSE66354',
 'GSE66359',
 'GSE66360',
 'GSE66387',
 'GSE66407',
 'GSE66476',
 'GSE66573',
 ...]

In [58]:
_dataset_count = adata.obs.groupby("dataset", observed=True)['celltype'].nunique()

_dataset_count[_dataset_count >= 6]

dataset
GSE3307       7
GSE42656      6
GSE88805      8
GSE89843      6
GSE100150     8
GSE123086    10
GSE174302     6
Name: celltype, dtype: int64

In [59]:
valid_pairs

MultiIndex([(     'Control', 'E-MEXP-3097'),
            (     'Control',  'E-MTAB-567'),
            (     'Control', 'E-MTAB-1030'),
            (     'Control', 'E-MTAB-1132'),
            (     'Control', 'E-MTAB-1516'),
            (     'Control', 'E-MTAB-1791'),
            (     'Control', 'E-MTAB-2312'),
            (     'Control', 'E-MTAB-2976'),
            (     'Control', 'E-MTAB-3338'),
            (     'Control', 'E-MTAB-3658'),
            ...
            ('DOID:0081087',   'GSE142698'),
            ('DOID:0081087',   'GSE171654'),
            ('DOID:0081087',   'GSE175701'),
            ('DOID:0081087',   'GSE183817'),
            ('DOID:0081087',   'GSE197907'),
            ('DOID:0081087',   'GSE198781'),
            ('DOID:0111394',    'GSE23075'),
            ('DOID:0111394',    'GSE32154'),
            ('DOID:0111535',    'GSE48120'),
            ('DOID:0111535',    'GSE48129')],
           names=['celltype', 'dataset'], length=4497)

In [104]:
import importlib
importlib.reload(tr_h)

In [106]:
adata_f_1 = tr_h.clean_adata_qc(adata_drop,n_samples=2, n_dt=2)

Nº of datasets with +2 control samples: 2364
Nº of datasets with +2 disease samples: 2130
Nº of datasets with +2 samples (control and disease): 2128
adata shape after filtering datasets with +2 samples: (100404, 20608)
Nº of passed diseases +2 294/ 296
Nº of passed dsaids +2 3815/ 3905

In [25]:
adata_f_1.shape

(121142, 20608)

In [29]:
adata_f_2 = tr_h.clean_adata_qc_new(adata,n_samples=2, n_dt=2)

Nº of datasets with +2 control samples: 0
Nº of datasets with +2 disease samples: 169
Nº of datasets with +2 samples (both): 0
adata shape after dataset filter: (0, 20608)
Removed 0 cells from pairs with <2 samples.
All cells filtered by pair-level constraint.

In [9]:
valid_pairs

MultiIndex([(     'Control', 'E-MEXP-3097'),
            (     'Control',  'E-MTAB-567'),
            (     'Control', 'E-MTAB-1030'),
            (     'Control', 'E-MTAB-1132'),
            (     'Control', 'E-MTAB-1516'),
            (     'Control', 'E-MTAB-1791'),
            (     'Control', 'E-MTAB-2312'),
            (     'Control', 'E-MTAB-2976'),
            (     'Control', 'E-MTAB-3338'),
            (     'Control', 'E-MTAB-3658'),
            ...
            ('DOID:0081087',   'GSE142698'),
            ('DOID:0081087',   'GSE171654'),
            ('DOID:0081087',   'GSE175701'),
            ('DOID:0081087',   'GSE183817'),
            ('DOID:0081087',   'GSE197907'),
            ('DOID:0081087',   'GSE198781'),
            ('DOID:0111394',    'GSE23075'),
            ('DOID:0111394',    'GSE32154'),
            ('DOID:0111535',    'GSE48120'),
            ('DOID:0111535',    'GSE48129')],
           names=['doid_id', 'dataset'], length=4512)

In [12]:
import pandas as pd
mi = pd.MultiIndex.from_frame(adata.obs[[disease_label, group_label]])

mask_pairs = mi.isin(valid_pairs)

In [15]:
import numpy as np
np.sum(mask_pairs)

121142

In [16]:
len(mask_pairs)

121142

In [17]:
adata.n_obs

121142

In [7]:
adata.obs.groupby("dataset")["doid_id"].count()

/tmp/ipykernel_456335/2037796854.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  adata.obs.groupby("dataset")["doid_id"].count()

dataset
E-MEXP-3097       5
E-MTAB-567       27
E-MTAB-1030      18
E-MTAB-1132     489
E-MTAB-1516      36
               ...
TCGA-LUSC       550
TCGA-PAAD       182
TCGA-PRAD       551
TCGA-STAD       407
TCGA-THCA      1698
Name: doid_id, Length: 2140, dtype: int64

In [73]:
adata_2 = sc.read("/aloy/home/ddalton/projects/scGPT_playground/data/pp_data-25-08-14-01/data.h5ad")

In [74]:
# what datasets am I missing ?

d2 = set(adata_2.obs["dataset_id"].unique())
d1 = set(adata.obs["dataset_id"].unique())

In [97]:
d_missing = (d2-d1)
adata_2.obs.query("dataset_id in @d_missing")["dsaid"].value_counts()

dsaid
DSA08970    585
DSA08971    583
DSA08981    551
DSA08973    550
DSA08960    546
           ...
DSA02758      0
DSA02757      0
DSA02755      0
DSA02731      0
DSA02780      0
Name: count, Length: 1159, dtype: int64

In [ ]:
mask_genes = tr_h.get_top_k_most_present_genes(
    adata, k=3501
)

In [106]:
import importlib
importlib.reload(pp)

In [109]:
from src.preprocessing import pipeline as pp 

bp = pp.bulk_processing()

for ds in d_missing:
    _dtype =  bp._classify_expr(adata_2.X[adata_2.obs["dataset_id"] == ds])
    print(ds, _dtype)

TCGA-PAAD log
GSE184053 log
TCGA-HNSC log
TCGA-LUSC log
GSE127853 log
TCGA-ESCA log
TCGA-PRAD log
GSE137327 log
GSE114245 log
TCGA-STAD log
TCGA-COAD log
TCGA-LUAD log
TCGA-GBM log
TCGA-CHOL log
GSE38003 log
TCGA-LIHC log
TCGA-BLCA log

In [ ]:
b_p = pp.bulk_processing(processing="linear", do_z_transform=False, agg_genes="median")

# process ids
d_types, df = b_p.get_processed_exp_prof(d_missing)

KeyboardInterrupt:

In [ ]:
import numpy as np
np.power(2, (adata_2.X[adata_2.obs["dataset_id"] == ds])) - 1

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [ ]:
df

In [105]:
_X = adata_2.X[adata_2.obs["dataset_id"] == list(d_missing)[0]]
_X = np.where(np.isnan(_X), 0, _X )
_X.max()

16.728246612790176

In [96]:
adata_2.obs["dataset_id"] in d_missing

TypeError: unhashable type: 'Series'

In [7]:
adata = adata[:, mask_genes]

In [53]:
import numpy as np

nan_thr= 0.9

non_nan_mask = ~np.isnan(adata.X)  & ~(adata.X==0) 
non_nan_mask_pct = np.sum(non_nan_mask, axis=1) / adata.X.shape[1]

# mask samples that have less than 30% non-NaN values
mask_samples_nan = non_nan_mask_pct >= nan_thr 

print(f"{nan_thr} Keeping {np.sum(mask_samples_nan)} samples out of {adata.X.shape[0]} ({np.sum(mask_samples_nan)/adata.X.shape[0]*100:.2f}%)")


zero_thr = 0.5
non_zero_mask = ~(adata.X==0) 
non_zero_mask_pct = np.sum(non_zero_mask, axis=1) / adata.X.shape[1]

# mask samples that have less than 30% non-NaN values
mask_samples_zero = non_zero_mask_pct >= zero_thr 

print(f"{zero_thr} Keeping {np.sum(mask_samples_zero)} samples out of {adata.X.shape[0]} ({np.sum(mask_samples_zero)/adata.X.shape[0]*100:.2f}%)")

mask_samples_comb = mask_samples_nan & mask_samples_zero
print(f"Combined: Keeping {np.sum(mask_samples_comb)} samples out of {adata.X.shape[0]} ({np.sum(mask_samples_comb)/adata.X.shape[0]*100:.2f}%)")

0.9 Keeping 100610 samples out of 111082 (90.57%)
0.5 Keeping 109791 samples out of 111082 (98.84%)
Combined: Keeping 100610 samples out of 111082 (90.57%)

In [9]:
for pct_thr in [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:
    non_zero_non_nan_mask = ~(adata.X==0) 
    non_zero_non_nan_mask_pct = np.sum(non_zero_non_nan_mask, axis=1) / adata.X.shape[1]

    # mask samples that have less than 30% non-NaN values
    mask_samples = non_zero_non_nan_mask_pct >= pct_thr 

    print(f"{pct_thr} Keeping {np.sum(mask_samples)} samples out of {adata.X.shape[0]} ({np.sum(mask_samples)/adata.X.shape[0]*100:.2f}%)")

0.3 Keeping 110630 samples out of 111082 (99.59%)
0.4 Keeping 110355 samples out of 111082 (99.35%)
0.5 Keeping 109791 samples out of 111082 (98.84%)
0.6 Keeping 109061 samples out of 111082 (98.18%)
0.7 Keeping 108535 samples out of 111082 (97.71%)
0.8 Keeping 108078 samples out of 111082 (97.30%)
0.9 Keeping 106747 samples out of 111082 (96.10%)

In [ ]:

# apply the mask to the AnnData object
adata[mask_samples, :].shape()

In [18]:
filtered_adata  = tr_h.clean_adata_qc(adata,n_samples=1, n_dt=4)

Nº of datasets with +1 control samples: 2111
Nº of datasets with +1 disease samples: 2111
Nº of datasets with +1 samples (control and disease): 2111
adata shape after filtering datasets with +1 samples: (111082, 3501)
Nº of passed diseases 142/ 292
Nº of passed dsaids 3395/ 3927

In [15]:
filtered_adata.obs["doid_id"].nunique()

196

In [45]:
adata_f.obs.query('doid_id == "DOID:1578"')["dataset_id"].unique()

['GSE166059', 'GSE40839', 'GSE81292']
Categories (1958, object): ['E-MEXP-3097', 'E-MTAB-567', 'E-MTAB-1030', 'E-MTAB-1132', ..., 'GSE224056', 'GSE225904', 'GSE226869', 'GSE227329']

In [50]:
adata_f.obs.query("dataset_id == 'GSE40839'")["doid_id"].unique()

['Control', 'DOID:1578']
Categories (196, object): ['Control', 'DOID:235', 'DOID:289', 'DOID:299', ..., 'DOID:0060224', 'DOID:0060901', 'DOID:0080199', 'DOID:0081087']

In [51]:
import importlib
importlib.reload(tr_h)

In [72]:
tr_h.clean_adata_qc(adata[adata.obs["library"]=="RNA-Seq"], n_samples=1, n_dt=2)

Nº of datasets with +1 control samples: 712
Nº of datasets with +1 disease samples: 712
Nº of datasets with +1 samples (control and disease): 712
adata shape after filtering datasets with +1 samples: (31606, 3501)
Nº of passed diseases 123/ 218
Nº of passed dsaids 1120/ 1261

View of AnnData object with n_obs × n_vars = 28425 × 3501
    obs: 'ids', 'dataset', 'dataset_id', 'batch', 'batch_id', 'dsaid', 'tissue', 'n_genes', 'disease', 'celltype', 'disease_study', 'library', 'doid_study', 'doid_id', 'do_id', 'doid_disease'
    var: 'gene_symbols', 'gene_name', 'index'

In [61]:

adata_q = adata[mask_samples, :]

adata_q = adata_q[adata_q.obs["library"]== "RNA-Seq"]
print(f"Nº of diseases before filtering: {adata_q.obs['doid_id'].nunique()}")

adata_f = tr_h.clean_adata_qc(adata_q, n_samples=1, n_dt=2)
print(f"Nº of diseases after filtering: {adata_f.obs['doid_id'].nunique()}")


# split
df_obs = adata_f.obs
test_obs = tr_h.split_stratified(
    df=df_obs,
    y_label="doid_id",  # should ALWAYS be on DOID! - OR  celltype be DOID! 
    group_label="dataset_id",
    split_size=10,
    seed=42,
)
tr_h.report_split(test_obs, disease_label="doid_id")





valid_obs = tr_h.split_stratified(
    df=test_obs[test_obs["test_split_1"]==0],
    y_label="doid_id",  # should ALWAYS be on DOID! - OR  celltype be DOID! 
    group_label="dataset_id",
    split_size=10,
    seed=42,
    new_label="valid_split_1"
)
tr_h.report_split(valid_obs, disease_label="doid_id", split_label="valid_split_1")

Nº of diseases before filtering: 215
Nº of datasets with +1 control samples: 661
Nº of datasets with +1 disease samples: 662
Nº of datasets with +1 samples (control and disease): 655
adata shape after filtering datasets with +1 samples: (27413, 3501)
Nº of passed diseases 118/ 214
Nº of passed dsaids 1024/ 1168
Nº of diseases after filtering: 119
df shape: (24492, 16)
df diseases: (13271, 16)
All Labels: 119 ['Control', 'DOID:0050156', 'DOID:0050700', 'DOID:0060161', 'DOID:0060488', 'DOID:0080199', 'DOID:0081087', 'DOID:10126', 'DOID:1024', 'DOID:10286', 'DOID:1040', 'DOID:10584', 'DOID:10591', 'DOID:10608', 'DOID:10652', 'DOID:10763', 'DOID:10871', 'DOID:10923', 'DOID:10941', 'DOID:11335', 'DOID:11555', 'DOID:11589', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:11934', 'DOID:11963', 'DOID:11984', 'DOID:12365', 'DOID:12377', 'DOID:12449', 'DOID:12704', 'DOID:12858', 'DOID:12894', 'DOID:12930', 'DOID:1312', 'DOID:13241', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1749', 'DOID:1883', 'DOID:1909', 'DOID:1921', 'DOID:1928', 'DOID:1932', 'DOID:1993', 'DOID:2043', 'DOID:2055', 'DOID:2224', 'DOID:2280', 'DOID:2348', 'DOID:235', 'DOID:2377', 'DOID:2378', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3044', 'DOID:3068', 'DOID:3070', 'DOID:3083', 'DOID:3261', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3498', 'DOID:3748', 'DOID:3777', 'DOID:3905', 'DOID:3908', 'DOID:3910', 'DOID:3911', 'DOID:3969', 'DOID:418', 'DOID:4450', 'DOID:4752', 'DOID:4905', 'DOID:5015', 'DOID:5409', 'DOID:5419', 'DOID:5517', 'DOID:552', 'DOID:5844', 'DOID:6000', 'DOID:635', 'DOID:6419', 'DOID:6688', 'DOID:684', 'DOID:687', 'DOID:7147', 'DOID:7148', 'DOID:768', 'DOID:769', 'DOID:8398', 'DOID:8469', 'DOID:8472', 'DOID:848', 'DOID:850', 'DOID:8534', 'DOID:8544', 'DOID:8552', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9111', 'DOID:9119', 'DOID:9352', 'DOID:9415', 'DOID:9538', 'DOID:9744', 'DOID:9778', 'DOID:9952', 'DOID:9970']
Remove Controls - Labels: 118 ['DOID:0050156', 'DOID:0050700', 'DOID:0060161', 'DOID:0060488', 'DOID:0080199', 'DOID:0081087', 'DOID:10126', 'DOID:1024', 'DOID:10286', 'DOID:1040', 'DOID:10584', 'DOID:10591', 'DOID:10608', 'DOID:10652', 'DOID:10763', 'DOID:10871', 'DOID:10923', 'DOID:10941', 'DOID:11335', 'DOID:11555', 'DOID:11589', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:11934', 'DOID:11963', 'DOID:11984', 'DOID:12365', 'DOID:12377', 'DOID:12449', 'DOID:12704', 'DOID:12858', 'DOID:12894', 'DOID:12930', 'DOID:1312', 'DOID:13241', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1749', 'DOID:1883', 'DOID:1909', 'DOID:1921', 'DOID:1928', 'DOID:1932', 'DOID:1993', 'DOID:2043', 'DOID:2055', 'DOID:2224', 'DOID:2280', 'DOID:2348', 'DOID:235', 'DOID:2377', 'DOID:2378', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3044', 'DOID:3068', 'DOID:3070', 'DOID:3083', 'DOID:3261', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3498', 'DOID:3748', 'DOID:3777', 'DOID:3905', 'DOID:3908', 'DOID:3910', 'DOID:3911', 'DOID:3969', 'DOID:418', 'DOID:4450', 'DOID:4752', 'DOID:4905', 'DOID:5015', 'DOID:5409', 'DOID:5419', 'DOID:5517', 'DOID:552', 'DOID:5844', 'DOID:6000', 'DOID:635', 'DOID:6419', 'DOID:6688', 'DOID:684', 'DOID:687', 'DOID:7147', 'DOID:7148', 'DOID:768', 'DOID:769', 'DOID:8398', 'DOID:8469', 'DOID:8472', 'DOID:848', 'DOID:850', 'DOID:8534', 'DOID:8544', 'DOID:8552', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9111', 'DOID:9119', 'DOID:9352', 'DOID:9415', 'DOID:9538', 'DOID:9744', 'DOID:9778', 'DOID:9952', 'DOID:9970']
Skipping DOID:8534 as already placed everything in train/test.
Nº of diseases in train split test_split_1:	119
Nº of diseases in test split test_split_1:	2
Nº of datasets in train split test_split_1:	580
Nº of datasets in test split test_split_1:	1
Nº of samples in train split test_split_1:	24466
Nº of samples in test split test_split_1:	26
df shape: (24466, 17)
df diseases: (13259, 17)
All Labels: 119 ['Control', 'DOID:0050156', 'DOID:0050700', 'DOID:0060161', 'DOID:0060488', 'DOID:0080199', 'DOID:0081087', 'DOID:10126', 'DOID:1024', 'DOID:10286', 'DOID:1040', 'DOID:10584', 'DOID:10591', 'DOID:10608', 'DOID:10652', 'DOID:10763', 'DOID:10871', 'DOID:10923', 'DOID:10941', 'DOID:11335', 'DOID:11555', 'DOID:11589', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:11934', 'DOID:11963', 'DOID:11984', 'DOID:12365', 'DOID:12377', 'DOID:12449', 'DOID:12704', 'DOID:12858', 'DOID:12894', 'DOID:12930', 'DOID:1312', 'DOID:13241', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1749', 'DOID:1883', 'DOID:1909', 'DOID:1921', 'DOID:1928', 'DOID:1932', 'DOID:1993', 'DOID:2043', 'DOID:2055', 'DOID:2224', 'DOID:2280', 'DOID:2348', 'DOID:235', 'DOID:2377', 'DOID:2378', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3044', 'DOID:3068', 'DOID:3070', 'DOID:3083', 'DOID:3261', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3498', 'DOID:3748', 'DOID:3777', 'DOID:3905', 'DOID:3908', 'DOID:3910', 'DOID:3911', 'DOID:3969', 'DOID:418', 'DOID:4450', 'DOID:4752', 'DOID:4905', 'DOID:5015', 'DOID:5409', 'DOID:5419', 'DOID:5517', 'DOID:552', 'DOID:5844', 'DOID:6000', 'DOID:635', 'DOID:6419', 'DOID:6688', 'DOID:684', 'DOID:687', 'DOID:7147', 'DOID:7148', 'DOID:768', 'DOID:769', 'DOID:8398', 'DOID:8469', 'DOID:8472', 'DOID:848', 'DOID:850', 'DOID:8534', 'DOID:8544', 'DOID:8552', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9111', 'DOID:9119', 'DOID:9352', 'DOID:9415', 'DOID:9538', 'DOID:9744', 'DOID:9778', 'DOID:9952', 'DOID:9970']
Remove Controls - Labels: 118 ['DOID:0050156', 'DOID:0050700', 'DOID:0060161', 'DOID:0060488', 'DOID:0080199', 'DOID:0081087', 'DOID:10126', 'DOID:1024', 'DOID:10286', 'DOID:1040', 'DOID:10584', 'DOID:10591', 'DOID:10608', 'DOID:10652', 'DOID:10763', 'DOID:10871', 'DOID:10923', 'DOID:10941', 'DOID:11335', 'DOID:11555', 'DOID:11589', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11725', 'DOID:11727', 'DOID:11934', 'DOID:11963', 'DOID:11984', 'DOID:12365', 'DOID:12377', 'DOID:12449', 'DOID:12704', 'DOID:12858', 'DOID:12894', 'DOID:12930', 'DOID:1312', 'DOID:13241', 'DOID:13922', 'DOID:14250', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1749', 'DOID:1883', 'DOID:1909', 'DOID:1921', 'DOID:1928', 'DOID:1932', 'DOID:1993', 'DOID:2043', 'DOID:2055', 'DOID:2224', 'DOID:2280', 'DOID:2348', 'DOID:235', 'DOID:2377', 'DOID:2378', 'DOID:2394', 'DOID:2841', 'DOID:289', 'DOID:3044', 'DOID:3068', 'DOID:3070', 'DOID:3083', 'DOID:3261', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3459', 'DOID:3498', 'DOID:3748', 'DOID:3777', 'DOID:3905', 'DOID:3908', 'DOID:3910', 'DOID:3911', 'DOID:3969', 'DOID:418', 'DOID:4450', 'DOID:4752', 'DOID:4905', 'DOID:5015', 'DOID:5409', 'DOID:5419', 'DOID:5517', 'DOID:552', 'DOID:5844', 'DOID:6000', 'DOID:635', 'DOID:6419', 'DOID:6688', 'DOID:684', 'DOID:687', 'DOID:7147', 'DOID:7148', 'DOID:768', 'DOID:769', 'DOID:8398', 'DOID:8469', 'DOID:8472', 'DOID:848', 'DOID:850', 'DOID:8534', 'DOID:8544', 'DOID:8552', 'DOID:8577', 'DOID:8893', 'DOID:9074', 'DOID:9111', 'DOID:9119', 'DOID:9352', 'DOID:9415', 'DOID:9538', 'DOID:9744', 'DOID:9778', 'DOID:9952', 'DOID:9970']
Skipping DOID:8534 as already placed everything in train/test.
Nº of diseases in train split valid_split_1:	119
Nº of diseases in test split valid_split_1:	2
Nº of datasets in train split valid_split_1:	579
Nº of datasets in test split valid_split_1:	1
Nº of samples in train split valid_split_1:	24460
Nº of samples in test split valid_split_1:	6

In [39]:
adata_f.obs.groupby("doid_id")["dataset"].nunique().sort_values()

/tmp/ipykernel_153703/2624498825.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  adata_f.obs.groupby("doid_id")["dataset"].nunique().sort_values()

doid_id
DOID:0060901       3
DOID:676           3
DOID:0060224       3
DOID:0050427       3
DOID:1107          3
                ...
DOID:10652        59
DOID:9074         63
DOID:2841         64
DOID:14330        66
Control         1958
Name: dataset, Length: 196, dtype: int64

In [42]:
df = adata_f.obs
y_label = "doid_id" 
group_label = "dataset_id"

# (tiny guard) each label must span ≥2 datasets to appear in both splits
_df_diseases = df[df[y_label] != "Control"]
print(f"df diseases: {_df_diseases.shape}")

ds_per_label = _df_diseases.groupby(y_label, observed=True)[group_label].nunique()
if (ds_per_label < 2).any():
    print(ds_per_label[ds_per_label < 2])
    raise ValueError("Some labels occur in <2 datasets; cannot place them in both splits.")

df diseases: (57716, 16)

In [28]:
test_obs

,ids,dataset,dataset_id,batch,batch_id,dsaid,tissue,n_genes,disease,celltype,disease_study,library,doid_study,doid_id,do_id,doid_disease,test_split_1
9,DSA00006.GSM3596906.Control,GSE126342,GSE126342,1512,1512,DSA00006,Skeletal muscle,19402,Control,Control,Myotonic Dystrophy Type 1,RNA-Seq,D,Control,Control,Control,0
10,DSA00006.GSM3596907.Control,GSE126342,GSE126342,1512,1512,DSA00006,Skeletal muscle,19402,Control,Control,Myotonic Dystrophy Type 1,RNA-Seq,D,Control,Control,Control,0
11,DSA00006.GSM3596908.Control,GSE126342,GSE126342,1512,1512,DSA00006,Skeletal muscle,19402,Control,Control,Myotonic Dystrophy Type 1,RNA-Seq,D,Control,Control,Control,0
12,DSA00006.GSM3596909.Control,GSE126342,GSE126342,1512,1512,DSA00006,Skeletal muscle,19402,Control,Control,Myotonic Dystrophy Type 1,RNA-Seq,D,Control,Control,Control,0
13,DSA00006.GSM3596910.Control,GSE126342,GSE126342,1512,1512,DSA00006,Skeletal muscle,19402,Control,Control,Myotonic Dystrophy Type 1,RNA-Seq,D,Control,Control,Control,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111077,DSA10302.GSM139471.Case,GSE6008,GSE6008,1354,1354,DSA10302,Ovary,12004,Ovarian Tumor,Ovarian Tumor,Ovarian Tumor,Microarray,D,DOID:2394,DOID:2394,ovarian cancer,0
111078,DSA10302.GSM139472.Case,GSE6008,GSE6008,1354,1354,DSA10302,Ovary,12004,Ovarian Tumor,Ovarian Tumor,Ovarian Tumor,Microarray,D,DOID:2394,DOID:2394,ovarian cancer,0
111079,DSA10302.GSM139473.Case,GSE6008,GSE6008,1354,1354,DSA10302,Ovary,12004,Ovarian Tumor,Ovarian Tumor,Ovarian Tumor,Microarray,D,DOID:2394,DOID:2394,ovarian cancer,0
111080,DSA10302.GSM139474.Case,GSE6008,GSE6008,1354,1354,DSA10302,Ovary,12004,Ovarian Tumor,Ovarian Tumor,Ovarian Tumor,Microarray,D,DOID:2394,DOID:2394,ovarian cancer,0
111081,DSA10302.GSM139475.Case,GSE6008,GSE6008,1354,1354,DSA10302,Ovary,12004,Ovarian Tumor,Ovarian Tumor,Ovarian Tumor,Microarray,D,DOID:2394,DOID:2394,ovarian cancer,0

In [20]:
adata_f.obs["doid_id"].nunique()

143

In [3]:
# quality control cleaning - enough samples and datasets
print("BEFORE QC - ADATA SHAPE:", adata.shape)
adata = tr_h.clean_adata_qc(adata,n_samples=1, n_dt=3)
print("AFTER QC - ADATA SHAPE:", adata.shape)

BEFORE QC - ADATA SHAPE: (121142, 20608)
Nº of datasets with +1 control samples: 2140
Nº of datasets with +1 disease samples: 2140
Nº of datasets with +1 samples (control and disease): 2140
adata shape after filtering datasets with +1 samples: (121142, 20608)
Nº of passed diseases 196/ 296
Nº of passed dsaids 3687/ 3986
AFTER QC - ADATA SHAPE: (112328, 20608)

In [11]:
import importlib
importlib.reload(tr_h)


split = 1


df_obs = adata.obs
new_obs = tr_h.split_stratified(
    df=df_obs,
    y_label="doid_id",
    group_label="dataset_id",
    split_size=10,
    seed=42,
)
tr_h.report_split(new_obs, disease_label="doid_id")

df shape: (112328, 16)
df diseases: (64108, 16)
All Labels: 197 ['Control', 'DOID:0050156', 'DOID:0050427', 'DOID:0050458', 'DOID:0050589', 'DOID:0050700', 'DOID:0050865', 'DOID:0050902', 'DOID:0060058', 'DOID:0060161', 'DOID:0060224', 'DOID:0060901', 'DOID:0080199', 'DOID:0081087', 'DOID:10223', 'DOID:1024', 'DOID:10241', 'DOID:10286', 'DOID:1040', 'DOID:10534', 'DOID:10584', 'DOID:10591', 'DOID:10608', 'DOID:10652', 'DOID:10763', 'DOID:10871', 'DOID:10923', 'DOID:10941', 'DOID:10976', 'DOID:1107', 'DOID:11100', 'DOID:11265', 'DOID:11335', 'DOID:11555', 'DOID:11589', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11723', 'DOID:11725', 'DOID:11727', 'DOID:11729', 'DOID:11934', 'DOID:11984', 'DOID:1206', 'DOID:12132', 'DOID:12177', 'DOID:12205', 'DOID:12217', 'DOID:12236', 'DOID:12306', 'DOID:12365', 'DOID:12377', 'DOID:12449', 'DOID:12689', 'DOID:12704', 'DOID:12858', 'DOID:12894', 'DOID:12930', 'DOID:1312', 'DOID:1319', 'DOID:13223', 'DOID:13241', 'DOID:13378', 'DOID:13515', 'DOID:13810', 'DOID:13922', 'DOID:13949', 'DOID:14203', 'DOID:14221', 'DOID:14250', 'DOID:14261', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1578', 'DOID:1580', 'DOID:1686', 'DOID:1712', 'DOID:1749', 'DOID:1793', 'DOID:1883', 'DOID:1909', 'DOID:1921', 'DOID:1926', 'DOID:1928', 'DOID:1993', 'DOID:2043', 'DOID:2055', 'DOID:2129', 'DOID:2224', 'DOID:2280', 'DOID:2283', 'DOID:2348', 'DOID:235', 'DOID:2377', 'DOID:2378', 'DOID:2394', 'DOID:2513', 'DOID:2723', 'DOID:2841', 'DOID:289', 'DOID:2957', 'DOID:2986', 'DOID:299', 'DOID:3008', 'DOID:3068', 'DOID:3069', 'DOID:3070', 'DOID:3082', 'DOID:3083', 'DOID:3151', 'DOID:3261', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3369', 'DOID:3429', 'DOID:3459', 'DOID:3491', 'DOID:3498', 'DOID:3571', 'DOID:3748', 'DOID:3905', 'DOID:3907', 'DOID:3908', 'DOID:3910', 'DOID:3911', 'DOID:3948', 'DOID:3963', 'DOID:3969', 'DOID:4007', 'DOID:4074', 'DOID:418', 'DOID:419', 'DOID:4448', 'DOID:4450', 'DOID:4465', 'DOID:4471', 'DOID:4483', 'DOID:4676', 'DOID:4752', 'DOID:4851', 'DOID:4905', 'DOID:4914', 'DOID:4947', 'DOID:4960', 'DOID:4971', 'DOID:5015', 'DOID:5082', 'DOID:5409', 'DOID:5419', 'DOID:5517', 'DOID:552', 'DOID:5520', 'DOID:5744', 'DOID:5844', 'DOID:6000', 'DOID:635', 'DOID:6419', 'DOID:6432', 'DOID:6543', 'DOID:676', 'DOID:684', 'DOID:687', 'DOID:7147', 'DOID:7148', 'DOID:769', 'DOID:824', 'DOID:8398', 'DOID:8469', 'DOID:848', 'DOID:8544', 'DOID:8552', 'DOID:8577', 'DOID:8632', 'DOID:8857', 'DOID:8866', 'DOID:8893', 'DOID:8997', 'DOID:9008', 'DOID:9074', 'DOID:9111', 'DOID:9119', 'DOID:9146', 'DOID:9206', 'DOID:9351', 'DOID:9352', 'DOID:9408', 'DOID:9415', 'DOID:9513', 'DOID:9538', 'DOID:9744', 'DOID:9778', 'DOID:986', 'DOID:9952', 'DOID:9970']
Remove Controls - Labels: 196 ['DOID:0050156', 'DOID:0050427', 'DOID:0050458', 'DOID:0050589', 'DOID:0050700', 'DOID:0050865', 'DOID:0050902', 'DOID:0060058', 'DOID:0060161', 'DOID:0060224', 'DOID:0060901', 'DOID:0080199', 'DOID:0081087', 'DOID:10223', 'DOID:1024', 'DOID:10241', 'DOID:10286', 'DOID:1040', 'DOID:10534', 'DOID:10584', 'DOID:10591', 'DOID:10608', 'DOID:10652', 'DOID:10763', 'DOID:10871', 'DOID:10923', 'DOID:10941', 'DOID:10976', 'DOID:1107', 'DOID:11100', 'DOID:11265', 'DOID:11335', 'DOID:11555', 'DOID:11589', 'DOID:11612', 'DOID:11714', 'DOID:11722', 'DOID:11723', 'DOID:11725', 'DOID:11727', 'DOID:11729', 'DOID:11934', 'DOID:11984', 'DOID:1206', 'DOID:12132', 'DOID:12177', 'DOID:12205', 'DOID:12217', 'DOID:12236', 'DOID:12306', 'DOID:12365', 'DOID:12377', 'DOID:12449', 'DOID:12689', 'DOID:12704', 'DOID:12858', 'DOID:12894', 'DOID:12930', 'DOID:1312', 'DOID:1319', 'DOID:13223', 'DOID:13241', 'DOID:13378', 'DOID:13515', 'DOID:13810', 'DOID:13922', 'DOID:13949', 'DOID:14203', 'DOID:14221', 'DOID:14250', 'DOID:14261', 'DOID:14330', 'DOID:1485', 'DOID:1520', 'DOID:1578', 'DOID:1580', 'DOID:1686', 'DOID:1712', 'DOID:1749', 'DOID:1793', 'DOID:1883', 'DOID:1909', 'DOID:1921', 'DOID:1926', 'DOID:1928', 'DOID:1993', 'DOID:2043', 'DOID:2055', 'DOID:2129', 'DOID:2224', 'DOID:2280', 'DOID:2283', 'DOID:2348', 'DOID:235', 'DOID:2377', 'DOID:2378', 'DOID:2394', 'DOID:2513', 'DOID:2723', 'DOID:2841', 'DOID:289', 'DOID:2957', 'DOID:2986', 'DOID:299', 'DOID:3008', 'DOID:3068', 'DOID:3069', 'DOID:3070', 'DOID:3082', 'DOID:3083', 'DOID:3151', 'DOID:3261', 'DOID:3310', 'DOID:3312', 'DOID:332', 'DOID:3369', 'DOID:3429', 'DOID:3459', 'DOID:3491', 'DOID:3498', 'DOID:3571', 'DOID:3748', 'DOID:3905', 'DOID:3907', 'DOID:3908', 'DOID:3910', 'DOID:3911', 'DOID:3948', 'DOID:3963', 'DOID:3969', 'DOID:4007', 'DOID:4074', 'DOID:418', 'DOID:419', 'DOID:4448', 'DOID:4450', 'DOID:4465', 'DOID:4471', 'DOID:4483', 'DOID:4676', 'DOID:4752', 'DOID:4851', 'DOID:4905', 'DOID:4914', 'DOID:4947', 'DOID:4960', 'DOID:4971', 'DOID:5015', 'DOID:5082', 'DOID:5409', 'DOID:5419', 'DOID:5517', 'DOID:552', 'DOID:5520', 'DOID:5744', 'DOID:5844', 'DOID:6000', 'DOID:635', 'DOID:6419', 'DOID:6432', 'DOID:6543', 'DOID:676', 'DOID:684', 'DOID:687', 'DOID:7147', 'DOID:7148', 'DOID:769', 'DOID:824', 'DOID:8398', 'DOID:8469', 'DOID:848', 'DOID:8544', 'DOID:8552', 'DOID:8577', 'DOID:8632', 'DOID:8857', 'DOID:8866', 'DOID:8893', 'DOID:8997', 'DOID:9008', 'DOID:9074', 'DOID:9111', 'DOID:9119', 'DOID:9146', 'DOID:9206', 'DOID:9351', 'DOID:9352', 'DOID:9408', 'DOID:9415', 'DOID:9513', 'DOID:9538', 'DOID:9744', 'DOID:9778', 'DOID:986', 'DOID:9952', 'DOID:9970']
Nº of diseases in train split test_split_1:	197
Nº of diseases in test split test_split_1:	197
Nº of datasets in train split test_split_1:	1737
Nº of datasets in test split test_split_1:	245
Nº of samples in train split test_split_1:	98433
Nº of samples in test split test_split_1:	13895

In [ ]:

# update observations with new column split
adata.obs = new_obs


# seperate data
adata_test = adata[adata.obs[f"test_split_{split}"] == 1].copy()
adata = adata[adata.obs[f"test_split_{split}"] == 0].copy()